"""
Seed rich authentic Kumbh Mela marketplace dataset into SQLite database.
Adds comprehensive items across:
- bazaar (Puja Samagri, Brassware, Copper vessels, Rudraksha, Gangajal, Dhoop, Vastram)
- hotel / stay (Dharamshalas, Ashrams, Bhakta Niwas, Yatri Bhavans)
- eatery / food (Annachhatras, Satvik Bhojanalays, Heritage Misal, Temple Prasad)
- rickshaw_bus / transport (Pre-paid Auto Stands, Electric Rickshaws, Pilgrimage Corridors)
"""
import sqlite3
import os
import uuid
from datetime import datetime, timezone

DB_PATH = os.path.join(os.path.dirname(__file__), "kumbhsetu_demo.db")

def now_iso():
    return datetime.now(timezone.utc).isoformat()

MARKET_ITEMS = [
    # ─── BAZAAR & STALLS ──────────────────────────────────────────────
    {
        "id": "bz-snan-kalash-01",
        "name": "Pure Brass Snan Kalash (1 Litre, Engraved)",
        "category": "bazaar",
        "subcategory": "Brassware & Ritual Vessels",
        "description": "Solid hand-engraved pure brass sacred bath kalash with traditional mango leaf carvings. Resistant to tarnishing.",
        "address": "Ramkund Ghat Stall #14, Panchavati, Nashik",
        "phone": "+91 98220 14411",
        "latitude": 19.9975,
        "longitude": 73.7898,
        "maps_link": "https://maps.google.com/?q=19.9975,73.7898",
        "reference_price": 240.0,
        "reported_price": 240.0,
        "rating": 4.9,
        "review_count": 142,
        "opening_hours": "05:00 AM - 09:30 PM",
        "known_for": "Fourth-generation Panchavati Coppersmiths",
        "image_url": "https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-gangajal-flask-02",
        "name": "Brahmagiri Origin Godavari Gangajal Brass Flask (500ml)",
        "category": "bazaar",
        "subcategory": "Gangajal & Samagri",
        "description": "Sealed holy Godavari water collected directly at Brahmagiri hill source. Leakproof hermetically sealed brass flask.",
        "address": "Stall #24, Godavari Puja Samagri Kendra, Ramkund Marg",
        "phone": "+91 98220 10492",
        "latitude": 19.9978,
        "longitude": 73.7902,
        "maps_link": "https://maps.google.com/?q=19.9978,73.7902",
        "reference_price": 80.0,
        "reported_price": 80.0,
        "rating": 4.9,
        "review_count": 188,
        "opening_hours": "05:30 AM - 10:00 PM",
        "known_for": "Mandir Trust Sealed Gangajal",
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-rudraksha-mala-03",
        "name": "Lab-Certified 5-Mukhi Himalayan Rudraksha Mala (108+1)",
        "category": "bazaar",
        "subcategory": "Sacred Beads & Rudraksha",
        "description": "X-Ray density tested authentic natural Himalayan 5-Mukhi Rudraksha beads. Energized at Trimbakeshwar Mahamrityunjaya shrine.",
        "address": "Stall #08, Sita Gufa Chowk, Panchavati, Nashik",
        "phone": "+91 98290 22033",
        "latitude": 19.9984,
        "longitude": 73.7915,
        "maps_link": "https://maps.google.com/?q=19.9984,73.7915",
        "reference_price": 190.0,
        "reported_price": 190.0,
        "rating": 4.9,
        "review_count": 210,
        "opening_hours": "06:00 AM - 09:00 PM",
        "known_for": "Lab Certificate of Authenticity Included",
        "image_url": "https://images.unsplash.com/photo-1614036417651-efe5912149d8?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-brass-diya-04",
        "name": "Hand-Cast Solid Brass Deepam Aarti Diya (Set of 2)",
        "category": "bazaar",
        "subcategory": "Aarti & Lamps",
        "description": "Heavy brass base oil diyas for continuous flame during sacred river snan and evening Godavari Maha Aarti.",
        "address": "Stall #12, Kapaleshwar Mandir Steps, Panchavati",
        "phone": "+91 98220 18822",
        "latitude": 19.9971,
        "longitude": 73.7891,
        "maps_link": "https://maps.google.com/?q=19.9971,73.7891",
        "reference_price": 180.0,
        "reported_price": 180.0,
        "rating": 4.8,
        "review_count": 96,
        "opening_hours": "05:00 AM - 09:30 PM",
        "known_for": "Kapaleshwar Artisan Guild",
        "image_url": "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-copper-jug-05",
        "name": "Hammered Pure Copper Tamra Patra & Lota Set",
        "category": "bazaar",
        "subcategory": "Copperware",
        "description": "Ayurvedic grade 99.4% pure hammered copper jug (1.2L) and lota for storing sacred Trimbakeshwar snan water.",
        "address": "Stall #03, Kushavarta Ghat Lane, Trimbakeshwar",
        "phone": "+91 98250 88110",
        "latitude": 19.9325,
        "longitude": 73.5305,
        "maps_link": "https://maps.google.com/?q=19.9325,73.5305",
        "reference_price": 280.0,
        "reported_price": 280.0,
        "rating": 4.8,
        "review_count": 78,
        "opening_hours": "06:00 AM - 08:30 PM",
        "known_for": "Direct Coppersmith Pricing",
        "image_url": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-mawa-peda-06",
        "name": "Nashik Fresh Mawa Peda & Panchamrit Prasad (250g Box)",
        "category": "bazaar",
        "subcategory": "Prasad & Sweets",
        "description": "FSSAI-certified holy temple prasad prepared in pure Desi cow ghee. High quality sealed packaging for traveling yatris.",
        "address": "Stall #31, Tapovan Sadhu Gram Bazar, Nashik",
        "phone": "+91 98220 29944",
        "latitude": 19.9912,
        "longitude": 73.8055,
        "maps_link": "https://maps.google.com/?q=19.9912,73.8055",
        "reference_price": 90.0,
        "reported_price": 90.0,
        "rating": 4.9,
        "review_count": 310,
        "opening_hours": "06:00 AM - 10:00 PM",
        "known_for": "Subsidized Civic Rate Counter",
        "image_url": "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-chandan-07",
        "name": "Mysore Pure Chandan Paste & Kesari Sandalwood Tika",
        "category": "bazaar",
        "subcategory": "Puja Essentials",
        "description": "Natural fragrant sandalwood block with stone rubbing slab and Kashmiri saffron tika for forehead mark.",
        "address": "Stall #19, Kalaram Mandir Road, Panchavati",
        "phone": "+91 98220 14411",
        "latitude": 19.9981,
        "longitude": 73.7925,
        "maps_link": "https://maps.google.com/?q=19.9981,73.7925",
        "reference_price": 120.0,
        "reported_price": 120.0,
        "rating": 4.9,
        "review_count": 135,
        "opening_hours": "05:30 AM - 09:00 PM",
        "known_for": "100% Organic Mysore Sandalwood",
        "image_url": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-handloom-dhoti-08",
        "name": "Handloom Saffron Peetambar Dhoti & Uttariya Set",
        "category": "bazaar",
        "subcategory": "Handloom & Vastram",
        "description": "Pure cotton 4-meter saffron dhoti with woven red border and matching uttariya shawl for snan rituals.",
        "address": "Stall #18, Main Godavari Ghat Road, Panchavati",
        "phone": "+91 98220 50198",
        "latitude": 19.9972,
        "longitude": 73.7895,
        "maps_link": "https://maps.google.com/?q=19.9972,73.7895",
        "reference_price": 210.0,
        "reported_price": 210.0,
        "rating": 4.8,
        "review_count": 84,
        "opening_hours": "06:00 AM - 09:30 PM",
        "known_for": "Yeola Handloom Weavers Collective",
        "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-akhand-diya-09",
        "name": "Wind-Proof Borosilicate Glass & Brass Akhand Diya",
        "category": "bazaar",
        "subcategory": "Aarti & Lamps",
        "description": "Heat-resistant borosilicate glass chimney with brass reservoir. Keeps flame glowing for 24+ hours at riverside.",
        "address": "Stall #07, Ramkund Steps, Sector 1, Nashik",
        "phone": "+91 98220 51667",
        "latitude": 19.9977,
        "longitude": 73.7899,
        "maps_link": "https://maps.google.com/?q=19.9977,73.7899",
        "reference_price": 160.0,
        "reported_price": 160.0,
        "rating": 4.8,
        "review_count": 67,
        "opening_hours": "05:00 AM - 10:00 PM",
        "known_for": "Ghat Wind-Resistant Certified",
        "image_url": "https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-camphor-10",
        "name": "Pure Organic Bhimseni Camphor (कापूर) 100g Airtight Jar",
        "category": "bazaar",
        "subcategory": "Puja Essentials",
        "description": "Zero black smoke, zero chemical residue untreated pure Bhimseni camphor flakes for divine aarti fragrance.",
        "address": "Stall #22, Sita Gumpha Marg, Panchavati",
        "phone": "+91 98220 51883",
        "latitude": 19.9983,
        "longitude": 73.7918,
        "maps_link": "https://maps.google.com/?q=19.9983,73.7918",
        "reference_price": 110.0,
        "reported_price": 110.0,
        "rating": 4.9,
        "review_count": 152,
        "opening_hours": "05:30 AM - 09:00 PM",
        "known_for": "Lab Tested 100% Pure Camphor",
        "image_url": "https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-tulsi-mala-11",
        "name": "Natural Tulsi Kanthi 108 Beads Mala & Cotton Gomukhi",
        "category": "bazaar",
        "subcategory": "Sacred Beads & Rudraksha",
        "description": "Natural fragrant sacred Tulsi wood beads with embroidered cotton Gomukhi Japa bag. Handcrafted by local artisans.",
        "address": "Stall #11, Kapaleshwar Mandir Back Road, Nashik",
        "phone": "+91 98220 52119",
        "latitude": 19.9973,
        "longitude": 73.7888,
        "maps_link": "https://maps.google.com/?q=19.9973,73.7888",
        "reference_price": 80.0,
        "reported_price": 80.0,
        "rating": 4.9,
        "review_count": 174,
        "opening_hours": "05:00 AM - 09:00 PM",
        "known_for": "Authentic Tulsi Wood Guarantee",
        "image_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-meru-yantra-12",
        "name": "Panchadhatu Maha Meru Shree Yantra (अभिमंत्रित)",
        "category": "bazaar",
        "subcategory": "Yantras & Coins",
        "description": "Sacred 3D geometric Meru Shree Yantra in 5 auspicious metals. Sanctified with Vedic Sri Sukta hymns.",
        "address": "Stall #15, Kalaram Mandir East Gate, Panchavati",
        "phone": "+91 98220 51667",
        "latitude": 19.9986,
        "longitude": 73.7928,
        "maps_link": "https://maps.google.com/?q=19.9986,73.7928",
        "reference_price": 250.0,
        "reported_price": 250.0,
        "rating": 4.9,
        "review_count": 118,
        "opening_hours": "06:00 AM - 08:30 PM",
        "known_for": "Trimbakeshwar Sanctified",
        "image_url": "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-coin-darbar-13",
        "name": "Simhastha 2027 Silver-Plated Ram Darbar Coin & Box",
        "category": "bazaar",
        "subcategory": "Yantras & Coins",
        "description": "Hallmarked commemorative medallion featuring Lord Ram, Sita, Lakshman, and Hanuman. Red velvet presentation case.",
        "address": "Stall #16, Ramkund Archway, Panchavati",
        "phone": "+91 98220 51882",
        "latitude": 19.9976,
        "longitude": 73.7901,
        "maps_link": "https://maps.google.com/?q=19.9976,73.7901",
        "reference_price": 150.0,
        "reported_price": 150.0,
        "rating": 4.8,
        "review_count": 112,
        "opening_hours": "06:00 AM - 09:30 PM",
        "known_for": "Official Simhastha Souvenir",
        "image_url": "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-dhoop-cups-14",
        "name": "Natural Guggul & Loban Hawan Dhoop Cups (Box of 12)",
        "category": "bazaar",
        "subcategory": "Puja Essentials",
        "description": "Pre-filled charcoal-free dhoop cups made from organic cow dung, guggul resin, and pure cow ghee. Burning time 30 mins.",
        "address": "Stall #27, Godavari Riverside Market, Panchavati",
        "phone": "+91 98220 51441",
        "latitude": 19.9979,
        "longitude": 73.7892,
        "maps_link": "https://maps.google.com/?q=19.9979,73.7892",
        "reference_price": 75.0,
        "reported_price": 75.0,
        "rating": 4.8,
        "review_count": 145,
        "opening_hours": "05:00 AM - 09:00 PM",
        "known_for": "100% Charcoal-Free Dhoop",
        "image_url": "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-bhadrakali-bhandar-15",
        "name": "Bhadrakali Gruh Vastu Bhandar (Puja Copper & Brass)",
        "category": "bazaar",
        "subcategory": "Puja Samagri",
        "description": "Historic Nashik wholesale & retail outlet for sacred utensils, brass ghantis, and complete snan kits.",
        "address": "79/80 Mirchi Bazar, Bhadrakali, Old Nashik",
        "phone": "+91 253 2571122",
        "latitude": 19.9932,
        "longitude": 73.7871,
        "maps_link": "https://maps.google.com/?q=19.9932,73.7871",
        "reference_price": 180.0,
        "reported_price": 180.0,
        "rating": 4.9,
        "review_count": 224,
        "opening_hours": "08:00 AM - 09:00 PM",
        "known_for": "Mirchi Bazar Heritage Shop (Est. 1952)",
        "image_url": "https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "bz-phule-market-16",
        "name": "Phule Market Lokhand & Tamba Bazar Stall",
        "category": "bazaar",
        "subcategory": "Metal Craft & Utensils",
        "description": "Authentic copper water carafes, tamra handis, and iron kadhais directly from coppersmith guild members.",
        "address": "Falke Road, Lokhand Bazar, Koknipura, Nashik",
        "phone": "+91 253 2504933",
        "latitude": 19.9915,
        "longitude": 73.7845,
        "maps_link": "https://maps.google.com/?q=19.9915,73.7845",
        "reference_price": 220.0,
        "reported_price": 220.0,
        "rating": 4.7,
        "review_count": 98,
        "opening_hours": "09:00 AM - 08:30 PM",
        "known_for": "Wholesale Direct Copper Pricing",
        "image_url": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },

    # ─── LOCAL STAYS & DHARAMSHALAS ────────────────────────────────────
    {
        "id": "stay-ramkund-yatri-01",
        "name": "Ramkund Yatri Bhavan & Dharamshala",
        "category": "hotel",
        "subcategory": "Dharamshala / Pilgrim Lodge",
        "description": "Official municipal registered pilgrim lodging 150m from Ramkund Ghat. Clean rooms, luggage locker facility, and 24/7 hot water.",
        "address": "Panchavati Ghat Road, Near Ramkund, Nashik 422003",
        "phone": "0253-2511422",
        "latitude": 19.9980,
        "longitude": 73.7905,
        "maps_link": "https://maps.google.com/?q=19.9980,73.7905",
        "reference_price": 250.0,
        "reported_price": 250.0,
        "rating": 4.7,
        "review_count": 184,
        "opening_hours": "24 Hours Check-in",
        "known_for": "Subsidized Pilgrim Rooms & Hot Water",
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "stay-trimbak-bhakta-02",
        "name": "Sri Trimbakeshwar Sansthan Bhakta Niwas",
        "category": "hotel",
        "subcategory": "Temple Trust Bhakta Niwas",
        "description": "Authorized trust accommodation for devotees visiting Trimbakeshwar Jyotirlinga. Subsidized rates, serene courtyard, Satvik prasad hall.",
        "address": "Mandir Complex Marg, Trimbakeshwar, Nashik 422212",
        "phone": "02594-233215",
        "latitude": 19.9331,
        "longitude": 73.5312,
        "maps_link": "https://maps.google.com/?q=19.9331,73.5312",
        "reference_price": 300.0,
        "reported_price": 300.0,
        "rating": 4.8,
        "review_count": 312,
        "opening_hours": "24 Hours Check-in",
        "known_for": "Sansthan Trust Subsidized Lodging",
        "image_url": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "stay-ahilyabai-holkar-03",
        "name": "Panchavati Ahilyabai Holkar Dharamshala",
        "category": "hotel",
        "subcategory": "Heritage Dharamshala",
        "description": "Historic charitable trust lodging built in traditional stone architecture. Safe lockers, dormitory halls, and attached private rooms.",
        "address": "Holkar Bridge Road, Panchavati, Nashik 422003",
        "phone": "0253-2512890",
        "latitude": 19.9965,
        "longitude": 73.7885,
        "maps_link": "https://maps.google.com/?q=19.9965,73.7885",
        "reference_price": 200.0,
        "reported_price": 200.0,
        "rating": 4.6,
        "review_count": 140,
        "opening_hours": "24 Hours",
        "known_for": "Charitable Free/Subsidized Pilgrims Stay",
        "image_url": "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "stay-kalaram-atithi-04",
        "name": "Kalaram Mandir Trust Atithi Bhavan",
        "category": "hotel",
        "subcategory": "Trust Atithi Bhavan",
        "description": "Spiritual guest house situated 80m from Kalaram Mandir. Quiet environment, elevator, clean linen, and pure drinking water.",
        "address": "Kalaram Temple East Gate, Panchavati, Nashik",
        "phone": "0253-2514930",
        "latitude": 19.9988,
        "longitude": 73.7932,
        "maps_link": "https://maps.google.com/?q=19.9988,73.7932",
        "reference_price": 450.0,
        "reported_price": 450.0,
        "rating": 4.8,
        "review_count": 92,
        "opening_hours": "06:00 AM - 11:00 PM",
        "known_for": "Serene Spiritual Environment",
        "image_url": "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "stay-tapovan-sadhugram-05",
        "name": "Tapovan Sadhu Gram Yatri Niwas",
        "category": "hotel",
        "subcategory": "Akhada & Yatri Shelter",
        "description": "Extensive lodging pavilion at Tapovan near Akhada camp. Massive hall with individual bedding, clean washrooms, and civic security post.",
        "address": "Tapovan Ring Road, Sector 4, Nashik 422011",
        "phone": "0253-2591000",
        "latitude": 19.9920,
        "longitude": 73.8070,
        "maps_link": "https://maps.google.com/?q=19.9920,73.8070",
        "reference_price": 150.0,
        "reported_price": 150.0,
        "rating": 4.5,
        "review_count": 210,
        "opening_hours": "24 Hours",
        "known_for": "Large Family & Group Accommodations",
        "image_url": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },

    # ─── EATERIES & SATVIK PRASAD ──────────────────────────────────────
    {
        "id": "food-ramkund-annakshetra-01",
        "name": "Ramkund Godavari Annachhatra (Subsidized Satvik Thali)",
        "category": "eatery",
        "subcategory": "Satvik Annachhatra",
        "description": "FSSAI-certified wholesome Mahaprasad thali: 4 Chapatis, Dal, 2 Sabzis, Rice, and fresh Kheer. Prepared with pure ingredients.",
        "address": "Opposite Ramkund Snan Ghat, Panchavati",
        "phone": "+91 253 2519900",
        "latitude": 19.9974,
        "longitude": 73.7899,
        "maps_link": "https://maps.google.com/?q=19.9974,73.7899",
        "reference_price": 70.0,
        "reported_price": 70.0,
        "rating": 4.9,
        "review_count": 480,
        "opening_hours": "11:00 AM - 03:30 PM, 06:30 PM - 09:30 PM",
        "known_for": "Civic Subsidized Satvik Thali",
        "image_url": "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "food-sadhana-misal-02",
        "name": "Sadhana Chulivarchi Misal & Bhakri (Heritage)",
        "category": "eatery",
        "subcategory": "Nashik Heritage Eatery",
        "description": "World-famous woodfire Chulivarchi Misal served with fresh Jowar/Bajra Bhakri, roasted papad, and chilled curd.",
        "address": "Gangapur-Savargaon Road, Near Someshwar Mandir, Nashik",
        "phone": "+91 98230 44922",
        "latitude": 20.0050,
        "longitude": 73.7380,
        "maps_link": "https://maps.google.com/?q=20.0050,73.7380",
        "reference_price": 120.0,
        "reported_price": 120.0,
        "rating": 4.8,
        "review_count": 1240,
        "opening_hours": "07:30 AM - 04:00 PM",
        "known_for": "Authentic Wood-fired Nashik Misal",
        "image_url": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "food-panchavati-gaurav-03",
        "name": "Panchavati Gaurav Pure Veg Satvik Dining Hall",
        "category": "eatery",
        "subcategory": "Satvik Dining Hall",
        "description": "Traditional sit-down silver platter Satvik feast: Rajasthani & Maharashtrian dishes, Puran Poli, Dal Baati, Shrikhand.",
        "address": "Tilak Road, Near CBS Bus Stand, Nashik",
        "phone": "+91 253 2570044",
        "latitude": 19.9922,
        "longitude": 73.7820,
        "maps_link": "https://maps.google.com/?q=19.9922,73.7820",
        "reference_price": 220.0,
        "reported_price": 220.0,
        "rating": 4.8,
        "review_count": 680,
        "opening_hours": "11:30 AM - 03:30 PM, 07:00 PM - 10:30 PM",
        "known_for": "Unlimited Pure Satvik Thali",
        "image_url": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "food-sayantara-04",
        "name": "Sayantara Sabudana Vada & Upvas Delights (Bhadrakali)",
        "category": "eatery",
        "subcategory": "Fast & Upvas Snacks",
        "description": "50+ year legacy heritage stall renowned across Maharashtra for crispy fasting Sabudana Vada with sweet cucumber chutney.",
        "address": "Bhadrakali Market, Old Nashik 422001",
        "phone": "+91 253 2578899",
        "latitude": 19.9930,
        "longitude": 73.7865,
        "maps_link": "https://maps.google.com/?q=19.9930,73.7865",
        "reference_price": 60.0,
        "reported_price": 60.0,
        "rating": 4.9,
        "review_count": 920,
        "opening_hours": "08:00 AM - 09:00 PM",
        "known_for": "Legendary Fasting Sabudana Vada",
        "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },

    # ─── RICKSHAW & TRANSIT CORRIDORS ─────────────────────────────────
    {
        "id": "transit-nashik-road-ramkund-01",
        "name": "Nashik Road Rly Stn → Ramkund Ghat (Pre-paid Auto)",
        "category": "rickshaw_bus",
        "subcategory": "Fixed Pre-Paid Corridor",
        "description": "Direct RTO-registered pre-paid auto rickshaw corridor connecting Railway Station to Ramkund Main Ghat. No bargaining allowed.",
        "address": "Pre-paid Booth #04, Nashik Road Station East Exit",
        "phone": "+91 253 2465500",
        "latitude": 19.9540,
        "longitude": 73.8420,
        "maps_link": "https://maps.google.com/?q=19.9540,73.8420",
        "reference_price": 140.0,
        "reported_price": 140.0,
        "rating": 4.9,
        "review_count": 520,
        "opening_hours": "24 Hours Service",
        "known_for": "RTO Regulated Fixed Fare Token",
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "transit-cbs-panchavati-02",
        "name": "Central Bus Stand (CBS) → Panchavati Ring (Electric Auto)",
        "category": "rickshaw_bus",
        "subcategory": "Electric Shuttle Stand",
        "description": "Eco-friendly zero-emission electric rickshaw shuttle connecting CBS central bus depot to Ramkund and Kalaram temple.",
        "address": "Platform Stand #01, CBS Depot, Old CBS Square",
        "phone": "+91 253 2574411",
        "latitude": 19.9925,
        "longitude": 73.7815,
        "maps_link": "https://maps.google.com/?q=19.9925,73.7815",
        "reference_price": 30.0,
        "reported_price": 30.0,
        "rating": 4.8,
        "review_count": 340,
        "opening_hours": "05:00 AM - 11:30 PM",
        "known_for": "Eco EV Shuttle (₹30 Fixed Seat)",
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    },
    {
        "id": "transit-ramkund-trimbak-03",
        "name": "Ramkund Ghat → Trimbakeshwar Jyotirlinga (AC Kumbh Bus)",
        "category": "rickshaw_bus",
        "subcategory": "Special Kumbh Express Bus",
        "description": "MSRTC high-frequency direct shuttle running every 15 minutes between Panchavati and Trimbakeshwar Kushavarta Ghat.",
        "address": "Nimani Bus Stand, Panchavati Ring Road, Nashik",
        "phone": "+91 253 2511200",
        "latitude": 19.9995,
        "longitude": 73.7940,
        "maps_link": "https://maps.google.com/?q=19.9995,73.7940",
        "reference_price": 55.0,
        "reported_price": 55.0,
        "rating": 4.8,
        "review_count": 890,
        "opening_hours": "04:30 AM - 11:00 PM (Every 15 mins)",
        "known_for": "MSRTC Official Pilgrimage Shuttle",
        "image_url": "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=600&q=80",
        "verification_status": "Kumbhveer Verified",
        "price_flagged": 0,
        "price_delta_percent": 0.0
    }
]

def seed_rich_data():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    insert_sql = """
        INSERT OR REPLACE INTO listings (
            id, name, category, subcategory, description, address, phone,
            latitude, longitude, maps_link, reference_price, reported_price,
            rating, review_count, opening_hours, known_for, image_url,
            verification_status, price_flagged, price_delta_percent,
            created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    
    count = 0
    now = now_iso()
    for item in MARKET_ITEMS:
        cursor.execute(insert_sql, (
            item["id"],
            item["name"],
            item["category"],
            item.get("subcategory"),
            item.get("description"),
            item.get("address"),
            item.get("phone"),
            item.get("latitude"),
            item.get("longitude"),
            item.get("maps_link"),
            item.get("reference_price"),
            item.get("reported_price"),
            item.get("rating"),
            item.get("review_count", 0),
            item.get("opening_hours"),
            item.get("known_for"),
            item.get("image_url"),
            item.get("verification_status", "Kumbhveer Verified"),
            item.get("price_flagged", 0),
            item.get("price_delta_percent", 0.0),
            now,
            now
        ))
        count += 1
        
    conn.commit()
    print(f"Successfully seeded {count} authentic Kumbh market items into {DB_PATH}")
    
    # Verify counts
    cursor.execute("SELECT category, count(*) FROM listings GROUP BY category")
    print("New Category Breakdown:", cursor.fetchall())
    conn.close()

if __name__ == "__main__":
    seed_rich_data()
