/**
 * Multi-lingual Translations for KumbhSetu
 * 11 Indian Languages. Crisp, punchy, active, zero fluff.
 */

export interface LanguageMeta {
  code: string;
  name: string;
  nativeName: string;
  region: string;
  shortCode: string;
}

export const SUPPORTED_LANGUAGES: LanguageMeta[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'All India', shortCode: 'EN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'राष्ट्रीय', shortCode: 'HI' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'महाराष्ट्र (नाशिक)', shortCode: 'MR' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'ગુજરાત', shortCode: 'GU' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'পশ্চিমবঙ্গ', shortCode: 'BN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'தமிழ்நாடு', shortCode: 'TA' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'ఆంధ్ర / తెలంగాణ', shortCode: 'TE' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'ಕರ್ನಾಟಕ', shortCode: 'KN' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'കേരളം', shortCode: 'ML' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'ਪੰਜਾਬ', shortCode: 'PA' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'ଓଡ଼ିଶା', shortCode: 'OR' },
];

export interface TranslationDictionary {
  appName: string;
  appTagline: string;
  welcome: string;
  selectLanguage: string;
  changeLanguage: string;
  listenVoice: string;
  speaking: string;
  save: string;
  cancel: string;
  search: string;
  call: string;
  direction: string;
  verified: string;
  fakeNews: string;
  underReview: string;
  shahiSnan: string;

  regTitle: string;
  regSubtitle: string;
  fullNameLabel: string;
  fullNamePlaceholder: string;
  phoneLabel: string;
  phonePlaceholder: string;
  dobLabel: string;
  dobPlaceholder: string;
  registerButton: string;
  welcomePilgrim: string;
  fillAllFields: string;

  tabHome: string;
  tabMarket: string;
  tabFare: string;
  tabHelp: string;

  homeBannerTitle: string;
  homeBannerSub: string;
  openPilgrimMapBtn: string;
  quickFeatures: string;
  cardPilgrimTitle: string;
  cardPilgrimDesc: string;
  cardMarketTitle: string;
  cardMarketDesc: string;
  cardFareTitle: string;
  cardFareDesc: string;
  cardComplaintTitle: string;
  cardComplaintDesc: string;
  crowdStatus: string;
  lowCrowd: string;
  modCrowd: string;
  highCrowd: string;
  darshanTimings: string;

  mapTitle: string;
  mapSubtitle: string;
  filterAll: string;
  filterGhats: string;
  filterTemples: string;
  filterFood: string;
  filterMedical: string;
  closeMap: string;

  marketTitle: string;
  marketSubtitle: string;
  allCategories: string;
  catChivda: string;
  catFood: string;
  catPuja: string;
  catGrapes: string;
  catStay: string;
  govtApprovedPrice: string;
  rateThisShop: string;
  submitRating: string;
  writeReview: string;
  shopContact: string;

  fareTitle: string;
  fareSubtitle: string;
  fromLocation: string;
  toLocation: string;
  selectRoute: string;
  sharedAuto: string;
  privateAuto: string;
  kumbhBus: string;
  perPerson: string;
  standardFoodRates: string;
  standardRatesNote: string;

  complaintTabTitle: string;
  complaintTabSubtitle: string;
  sectionReportOvercharge: string;
  sectionRumorBuster: string;
  sectionEmergency: string;
  selectCategory: string;
  vehicleOrShop: string;
  standardAmt: string;
  chargedAmt: string;
  locationPlace: string;
  submitComplaint: string;
  complaintSuccess: string;
  reportRumorBtn: string;
  rumorPlaceholder: string;
  emergencyDesc: string;
}

export const TRANSLATIONS: Record<string, TranslationDictionary> = {
  en: {
    appName: 'KumbhSetu',
    appTagline: 'Nashik-Trimbakeshwar Kumbh 2027',
    welcome: 'Kumbh Mela Guide',
    selectLanguage: 'Choose Language',
    changeLanguage: 'Switch Language',
    listenVoice: 'Audio Guide',
    speaking: 'Playing...',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    call: 'Call',
    direction: 'Route',
    verified: 'Verified',
    fakeNews: 'False Claim',
    underReview: 'Verifying',
    shahiSnan: 'Shahi Snan Dates',

    regTitle: 'Pilgrim Sign-in',
    regSubtitle: 'Name, phone, and birth date',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'e.g. Ramesh Sharma',
    phoneLabel: 'Mobile Number',
    phonePlaceholder: '10-digit number',
    dobLabel: 'Birth Date',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'Continue',
    welcomePilgrim: 'Pilgrim',
    fillAllFields: 'Fill all required fields',

    tabHome: 'Home',
    tabMarket: 'Market',
    tabFare: 'Fares',
    tabHelp: 'Help & SOS',

    homeBannerTitle: 'Pilgrimage & Sacred Ghats',
    homeBannerSub: 'Ramkund, Trimbakeshwar, Panchavati & Kalaram Mandir',
    openPilgrimMapBtn: 'Open Map',
    quickFeatures: 'Key Facilities',
    cardPilgrimTitle: 'Ghat & Temple Map',
    cardPilgrimDesc: 'Live crowd levels, shrines, and bathing ghats',
    cardMarketTitle: 'Local Bazaar',
    cardMarketDesc: 'Verified local specialties, eateries, and shops',
    cardFareTitle: 'Fare Guide',
    cardFareDesc: 'Approved transit tariffs and standard food rates',
    cardComplaintTitle: 'Reports & Fact-Checks',
    cardComplaintDesc: 'Overcharge reporting, verified news, and SOS',
    crowdStatus: 'Crowd',
    lowCrowd: 'Low Rush',
    modCrowd: 'Moderate Rush',
    highCrowd: 'Heavy Rush',
    darshanTimings: 'Timings',

    mapTitle: 'Pilgrim Map',
    mapSubtitle: 'OpenStreetMap navigation',
    filterAll: 'All',
    filterGhats: 'Ghats',
    filterTemples: 'Temples',
    filterFood: 'Meal Centers',
    filterMedical: 'Medical',
    closeMap: 'Close Map',

    marketTitle: 'Local Bazaar',
    marketSubtitle: 'Registered vendors and fixed tariffs',
    allCategories: 'All',
    catChivda: 'Chivda & Snacks',
    catFood: 'Meals & Misal',
    catPuja: 'Puja Items',
    catGrapes: 'Grapes & Raisins',
    catStay: 'Dharamshala & Stay',
    govtApprovedPrice: 'Approved Rate',
    rateThisShop: 'Rate Vendor',
    submitRating: 'Submit Rating',
    writeReview: 'Write feedback',
    shopContact: 'Contact Vendor',

    fareTitle: 'Transit & Price Directory',
    fareSubtitle: 'Official government tariffs',
    fromLocation: 'From',
    toLocation: 'To',
    selectRoute: 'Route Tariff',
    sharedAuto: 'Shared Auto',
    privateAuto: 'Private Auto',
    kumbhBus: 'Citylink Bus',
    perPerson: 'Per person',
    standardFoodRates: 'Standard Rates',
    standardRatesNote: 'Government ceiling rates. Report violations in Help tab.',

    complaintTabTitle: 'Reports & Emergency',
    complaintTabSubtitle: '24x7 Administration monitoring',
    sectionReportOvercharge: 'Report Overcharging',
    sectionRumorBuster: 'Fact-Check Feed',
    sectionEmergency: 'Emergency Contacts (SOS)',
    selectCategory: 'Category',
    vehicleOrShop: 'Vehicle No. or Vendor Name',
    standardAmt: 'Approved Rate (₹)',
    chargedAmt: 'Charged Rate (₹)',
    locationPlace: 'Location',
    submitComplaint: 'Submit Report',
    complaintSuccess: 'Report submitted. Case token generated.',
    reportRumorBtn: 'Submit Claim for Fact-Check',
    rumorPlaceholder: 'Enter claim or text to verify...',
    emergencyDesc: 'Direct-dial emergency lines',
  },

  hi: {
    appName: 'कुंभसेतु',
    appTagline: 'नासिक-त्र्यंबकेश्वर कुंभ 2027',
    welcome: 'कुंभ मेला मार्गदर्शिका',
    selectLanguage: 'भाषा चुनें',
    changeLanguage: 'भाषा बदलें',
    listenVoice: 'ऑडियो गाइड',
    speaking: 'ऑडियो चालू...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    search: 'खोजें...',
    call: 'कॉल करें',
    direction: 'मार्ग',
    verified: 'प्रमाणित',
    fakeNews: 'भ्रामक दावा',
    underReview: 'जांच जारी',
    shahiSnan: 'शाही स्नान तिथियां',

    regTitle: 'तीर्थयात्री प्रवेश',
    regSubtitle: 'नाम, मोबाइल नंबर और जन्म तिथि',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'उदा. रमेश शर्मा',
    phoneLabel: 'मोबाइल नंबर',
    phonePlaceholder: '10 अंकों का नंबर',
    dobLabel: 'जन्म तिथि',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'आगे बढ़ें',
    welcomePilgrim: 'तीर्थयात्री',
    fillAllFields: 'सभी विवरण भरें',

    tabHome: 'होम',
    tabMarket: 'बाज़ार',
    tabFare: 'किराया',
    tabHelp: 'शिकायत व SOS',

    homeBannerTitle: 'पवित्र तीर्थ व स्नान घाट',
    homeBannerSub: 'रामकुंड, त्र्यंबकेश्वर, पंचवटी व कालाराम मंदिर',
    openPilgrimMapBtn: 'नक्शा खोलें',
    quickFeatures: 'प्रमुख सुविधाएं',
    cardPilgrimTitle: 'तीर्थ व घाट नक्शा',
    cardPilgrimDesc: 'मंदिर, स्नान घाट व लाइव भीड़ स्थिति',
    cardMarketTitle: 'स्थानीय बाज़ार',
    cardMarketDesc: 'सत्यापित नासिक चिवड़ा, भोजन व दुकानें',
    cardFareTitle: 'किराया सूची',
    cardFareDesc: 'तय ऑटो-बस किराया व खान-पान के सही दाम',
    cardComplaintTitle: 'शिकायत व तथ्य जांच',
    cardComplaintDesc: 'ज्यादा वसूली रिपोर्ट, सही सूचना व आपात नंबर',
    crowdStatus: 'भीड़',
    lowCrowd: 'कम भीड़',
    modCrowd: 'मध्यम भीड़',
    highCrowd: 'अधिक भीड़',
    darshanTimings: 'दर्शन समय',

    mapTitle: 'तीर्थ नक्शा',
    mapSubtitle: 'सटीक नेविगेशन',
    filterAll: 'सभी',
    filterGhats: 'घाट',
    filterTemples: 'मंदिर',
    filterFood: 'अन्नछत्र',
    filterMedical: 'चिकित्सा',
    closeMap: 'नक्शा बंद करें',

    marketTitle: 'स्थानीय बाज़ार',
    marketSubtitle: 'सत्यापित दुकानें और तय दरें',
    allCategories: 'सभी',
    catChivda: 'चिवड़ा व मिठाई',
    catFood: 'मिसळ व भोजन',
    catPuja: 'पूजा सामग्री',
    catGrapes: 'अंगूर व किशमिश',
    catStay: 'धर्मशाला व निवास',
    govtApprovedPrice: 'सरकारी तय दर',
    rateThisShop: 'रेटिंग दें',
    submitRating: 'रेटिंग भेजें',
    writeReview: 'अनुभव लिखें',
    shopContact: 'संपर्क करें',

    fareTitle: 'सरकारी किराया व दर सूची',
    fareSubtitle: 'प्रशासन द्वारा तय दरें',
    fromLocation: 'कहाँ से',
    toLocation: 'कहाँ तक',
    selectRoute: 'रूट किराया',
    sharedAuto: 'शेयरिंग ऑटो',
    privateAuto: 'प्राइवेट ऑटो',
    kumbhBus: 'सिटीलिंक बस',
    perPerson: 'प्रति व्यक्ति',
    standardFoodRates: 'तय मानक दरें',
    standardRatesNote: 'सरकारी तय दरें। उल्लंघन की शिकायत हेल्प टैब में करें।',

    complaintTabTitle: 'शिकायत व आपात सहायता',
    complaintTabSubtitle: '24x7 प्रशासन निगरानी',
    sectionReportOvercharge: 'अधिक पैसे वसूली की शिकायत',
    sectionRumorBuster: 'तथ्य जांच (Fact-Check)',
    sectionEmergency: 'आपातकालीन हेल्पलाइन (SOS)',
    selectCategory: 'श्रेणी',
    vehicleOrShop: 'गाड़ी नंबर या दुकानदार का नाम',
    standardAmt: 'सरकारी दर (₹)',
    chargedAmt: 'मांगे गए पैसे (₹)',
    locationPlace: 'स्थान',
    submitComplaint: 'शिकायत दर्ज करें',
    complaintSuccess: 'शिकायत दर्ज। टोकन जारी किया गया।',
    reportRumorBtn: 'जांच के लिए भेजें',
    rumorPlaceholder: 'सत्यापन के लिए सूचना दर्ज करें...',
    emergencyDesc: 'आपातकालीन सीधी कॉल',
  },

  mr: {
    appName: 'कुंभसेतु',
    appTagline: 'नाशिक-त्र्यंबकेश्वर कुंभमेळा २०२७',
    welcome: 'कुंभमेळा मार्गदर्शक',
    selectLanguage: 'भाषा निवडा',
    changeLanguage: 'भाषा बदला',
    listenVoice: 'ऑडिओ गाईड',
    speaking: 'चालू आहे...',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    search: 'शोधा...',
    call: 'कॉल करा',
    direction: 'मार्ग',
    verified: 'प्रमाणित',
    fakeNews: 'खोटा दावा',
    underReview: 'तपास सुरू',
    shahiSnan: 'शाही स्नान तारखा',

    regTitle: 'भाविक नोंदणी',
    regSubtitle: 'नाव, मोबाईल क्रमांक आणि जन्मतारीख',
    fullNameLabel: 'पूर्ण नाव',
    fullNamePlaceholder: 'उदा. गणेश पाटील',
    phoneLabel: 'मोबाईल क्रमांक',
    phonePlaceholder: '१० अंकी क्रमांक',
    dobLabel: 'जन्मतारीख',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'पुढे जा',
    welcomePilgrim: 'भाविक',
    fillAllFields: 'सर्व माहिती भरा',

    tabHome: 'मुख्य',
    tabMarket: 'बाजार',
    tabFare: 'भाडे',
    tabHelp: 'तक्रार व SOS',

    homeBannerTitle: 'पवित्र तीर्थ व स्नान घाट',
    homeBannerSub: 'रामकुंड, त्र्यंबकेश्वर, पंचवटी व काळाराम मंदिर',
    openPilgrimMapBtn: 'नकाशा उघडा',
    quickFeatures: 'प्रमुख सुविधा',
    cardPilgrimTitle: 'तीर्थ व घाट नकाशा',
    cardPilgrimDesc: 'मंदिरे, स्नान घाट आणि थेट गर्दी स्थिती',
    cardMarketTitle: 'स्थानिक बाजार',
    cardMarketDesc: 'प्रसिद्ध चिवडा, द्राक्षे, खाद्यपदार्थ व दुकाने',
    cardFareTitle: 'भाडे सूची',
    cardFareDesc: 'रिक्षा-बस भाडे आणि खाण्यापिण्याचे निश्चित दर',
    cardComplaintTitle: 'तक्रार व अफवा निवारण',
    cardComplaintDesc: 'जास्त भाडे तक्रार, खरी बातमी आणि SOS',
    crowdStatus: 'गर्दी',
    lowCrowd: 'कमी गर्दी',
    modCrowd: 'मध्यम गर्दी',
    highCrowd: 'जास्त गर्दी',
    darshanTimings: 'दर्शन वेळ',

    mapTitle: 'तीर्थ नकाशा',
    mapSubtitle: 'अचूक मार्गदर्शन',
    filterAll: 'सर्व',
    filterGhats: 'घाट',
    filterTemples: 'मंदिरे',
    filterFood: 'अन्नछत्र',
    filterMedical: 'वैद्यकीय',
    closeMap: 'नकाशा बंद करा',

    marketTitle: 'स्थानिक बाजार',
    marketSubtitle: 'नोंदणीकृत दुकाने व ठरलेले दर',
    allCategories: 'सर्व',
    catChivda: 'चिवडा व मिठाई',
    catFood: 'मिसळ व जेवण',
    catPuja: 'पूजा साहित्य',
    catGrapes: 'द्राक्षे व मनुका',
    catStay: 'धर्मशाळा व मुक्काम',
    govtApprovedPrice: 'शासकीय दर',
    rateThisShop: 'रेटिंग द्या',
    submitRating: 'रेटिंग सबमिट करा',
    writeReview: 'अनुभव लिहा',
    shopContact: 'संपर्क साधा',

    fareTitle: 'अधिकृत भाडे व दर सूची',
    fareSubtitle: 'प्रशासनाने निश्चित केलेले दर',
    fromLocation: 'कुठून',
    toLocation: 'कुठे',
    selectRoute: 'रूट भाडे',
    sharedAuto: 'शेअरिंग रिक्षा',
    privateAuto: 'प्रायव्हेट रिक्षा',
    kumbhBus: 'सिटीलिंक बस',
    perPerson: 'प्रति व्यक्ती',
    standardFoodRates: 'निश्चित दर',
    standardRatesNote: 'शासकीय कमाल दर. तक्रार नोंदवण्यासाठी हेल्प टॅब वापरा.',

    complaintTabTitle: 'तक्रार व आपत्कालीन मदत',
    complaintTabSubtitle: '२४ तास प्रशासन निगराणी',
    sectionReportOvercharge: 'जास्त पैसे उकळल्याची तक्रार',
    sectionRumorBuster: 'अफवा तपास (Fact-Check)',
    sectionEmergency: 'आपत्कालीन क्रमांक (SOS)',
    selectCategory: 'प्रकार',
    vehicleOrShop: 'गाडी नंबर किंवा दुकानाचे नाव',
    standardAmt: 'सरकारी दर (₹)',
    chargedAmt: 'घेतलेले पैसे (₹)',
    locationPlace: 'ठिकाण',
    submitComplaint: 'तक्रार नोंदवा',
    complaintSuccess: 'तक्रार नोंदवली. टोकन क्रमांक जारी.',
    reportRumorBtn: 'तपासासाठी पाठवा',
    rumorPlaceholder: 'माहिती येथे लिहा...',
    emergencyDesc: 'थेट आपत्कालीन कॉल',
  },

  gu: {
    appName: 'કુંભસેતુ',
    appTagline: 'નાસિક-ત્ર્યંબકેશ્વર કુંભ ૨૦૨૭',
    welcome: 'કુંભ મેળો ગાઇડ',
    selectLanguage: 'ભાષા પસંદ કરો',
    changeLanguage: 'ભાષા બદલો',
    listenVoice: 'ઑડિયો ગાઇડ',
    speaking: 'ચાલુ છે...',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    search: 'શોધો...',
    call: 'કૉલ',
    direction: 'માર્ગ',
    verified: 'પ્રમાણિત',
    fakeNews: 'ખોટો દાવો',
    underReview: 'તપાસ ચાલુ',
    shahiSnan: 'શાહી સ્નાન તારીખો',

    regTitle: 'યાત્રાળુ નોંધણી',
    regSubtitle: 'નામ, મોબાઇલ નંબર અને જન્મ તારીખ',
    fullNameLabel: 'પૂરું નામ',
    fullNamePlaceholder: 'દા.ત. પરેશ શાહ',
    phoneLabel: 'મોબાઇલ નંબર',
    phonePlaceholder: '૧૦ અંકનો નંબર',
    dobLabel: 'જન્મ તારીખ',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'આગળ વધો',
    welcomePilgrim: 'યાત્રાળુ',
    fillAllFields: 'બધી વિગતો ભરો',

    tabHome: 'હોમ',
    tabMarket: 'બજાર',
    tabFare: 'ભાડું',
    tabHelp: 'ફરિયાદ व SOS',

    homeBannerTitle: 'પવિત્ર તીર્થ અને સ્નાન ઘાટ',
    homeBannerSub: 'રામકુંડ, ત્ર્યંબકેશ્વર, પંચવટી દર્શન',
    openPilgrimMapBtn: 'નકશો ખોલો',
    quickFeatures: 'મુખ્ય સેવાઓ',
    cardPilgrimTitle: 'તીર્થ અને ઘાટ નકશો',
    cardPilgrimDesc: 'મંદિરો, ઘાટ અને ભીડની સ્થિતિ',
    cardMarketTitle: 'સ્થાનિક બજાર',
    cardMarketDesc: 'ચેવડો, દ્રાક્ષ, પૂજા સામગ્રી અને ભોજન',
    cardFareTitle: 'ભાડું અને ભાવ સૂચિ',
    cardFareDesc: 'રિક્ષા-બસ ભાડું અને ભોજનના નક્કી ભાવ',
    cardComplaintTitle: 'ફરિયાદ અને અફવા તપાસ',
    cardComplaintDesc: 'વધુ રૂપિયા વસૂલવાની ફરિયાદ અને SOS',
    crowdStatus: 'ભીડ',
    lowCrowd: 'ઓછી ભીડ',
    modCrowd: 'મધ્યમ ભીડ',
    highCrowd: 'ભારે ભીડ',
    darshanTimings: 'દર્શન સમય',

    mapTitle: 'તીર્થ નકશો',
    mapSubtitle: 'ચોક્કસ માર્ગદર્શન',
    filterAll: 'બધા',
    filterGhats: 'ઘાટ',
    filterTemples: 'મંદિરો',
    filterFood: 'અન્નક્ષેત્ર',
    filterMedical: 'તબીબી',
    closeMap: 'નકશો બંધ કરો',

    marketTitle: 'સ્થાનિક બજાર',
    marketSubtitle: 'પ્રમાણિત દુકાનો અને સરકારી ભાવ',
    allCategories: 'બધા',
    catChivda: 'ચેવડો અને મીઠાઈ',
    catFood: 'મિસળ અને ભોજન',
    catPuja: 'પૂજા સામગ્રી',
    catGrapes: 'દ્રાક્ષ અને કિસમિસ',
    catStay: 'ધર્મશાળા',
    govtApprovedPrice: 'સરકારી ભાવ',
    rateThisShop: 'રેટિંગ આપો',
    submitRating: 'રેટિંગ મોકલો',
    writeReview: 'અનુભવ લખો',
    shopContact: 'સંપર્ક કરો',

    fareTitle: 'સત્તાવાર ભાડું અને ભાવ સૂચિ',
    fareSubtitle: 'તંત્ર દ્વારા નક્કી કરેલા દર',
    fromLocation: 'ક્યાંથી',
    toLocation: 'ક્યાં',
    selectRoute: 'રૂટ ભાડું',
    sharedAuto: 'શેરિંગ રિક્ષા',
    privateAuto: 'પ્રાઇવેટ રિક્ષા',
    kumbhBus: 'સિટી બસ',
    perPerson: 'વ્યક્તિ દીઠ',
    standardFoodRates: 'નક્કી ભાવ',
    standardRatesNote: 'સરકારી મહત્તમ દર. હેલ્પ ટેબમાં ફરિયાદ કરો.',

    complaintTabTitle: 'ફરિયાદ અને ઇમરજન્સી',
    complaintTabSubtitle: '૨૪ કલાક તંત્ર દેખરેખ',
    sectionReportOvercharge: 'વધુ પૈસા લેવાની ફરિયાદ',
    sectionRumorBuster: 'અફવા તપાસ (Fact-Check)',
    sectionEmergency: 'ઇમરજન્સી હેલ્પલાઇન (SOS)',
    selectCategory: 'પ્રકાર',
    vehicleOrShop: 'વાહન નંબર અથવા દુકાનનું નામ',
    standardAmt: 'સરકારી દર (₹)',
    chargedAmt: 'લીધેલા પૈસા (₹)',
    locationPlace: 'સ્થળ',
    submitComplaint: 'ફરિયાદ નોંધાવો',
    complaintSuccess: 'ફરિયાદ નોંધાઈ. ટોકન જારી.',
    reportRumorBtn: 'તપાસ માટે મોકલો',
    rumorPlaceholder: 'માહિતી અહીં લખો...',
    emergencyDesc: 'તાત્કાલિક ઇમરજન્સી કૉલ',
  },

  bn: {
    appName: 'কুম্ভসেতু',
    appTagline: 'নাসিক-ত্র্যম্বকেশ্বর কুম্ভ ২০২৭',
    welcome: 'কুম্ভমেলা গাইড',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    changeLanguage: 'ভাষা পরিবর্তন',
    listenVoice: 'অডিও গাইড',
    speaking: 'চলছে...',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    search: 'অনুসন্ধান...',
    call: 'কল',
    direction: 'রুট',
    verified: 'যাচাইকৃত',
    fakeNews: 'ভুয়ো দাবি',
    underReview: 'তদন্তাধীন',
    shahiSnan: 'শাহী স্নান দিনক্ষণ',

    regTitle: 'তীর্থযাত্রী প্রবেশ',
    regSubtitle: 'নাম, মোবাইল নম্বর ও জন্ম তারিখ',
    fullNameLabel: 'পুরো নাম',
    fullNamePlaceholder: 'যেমন: শুভাশীষ রায়',
    phoneLabel: 'মোবাইল নম্বর',
    phonePlaceholder: '১০ ডিজিটের নম্বর',
    dobLabel: 'জন্ম তারিখ',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'এগিয়ে যান',
    welcomePilgrim: 'তীর্থযাত্রী',
    fillAllFields: 'সব তথ্য পূরণ করুন',

    tabHome: 'হোম',
    tabMarket: 'বাজার',
    tabFare: 'ভাড়া',
    tabHelp: 'অভিযোগ ও SOS',

    homeBannerTitle: 'পবিত্র তীর্থ ও স্নান ঘাট',
    homeBannerSub: 'রামকুণ্ড, ত্র্যম্বকেশ্বর, পঞ্চবটী দর্শন',
    openPilgrimMapBtn: 'মানচিত্র খুলুন',
    quickFeatures: 'প্রধান সেবা সমূহ',
    cardPilgrimTitle: 'তীর্থ ও ঘাট মানচিত্র',
    cardPilgrimDesc: 'মন্দির, স্নান ঘাট ও লাইভ ভিড়',
    cardMarketTitle: 'স্থানীয় বাজার',
    cardMarketDesc: 'বিখ্যাত চিঁড়ে, আঙুর ও খাবারের দোকান',
    cardFareTitle: 'ভাড়া তালিকা',
    cardFareDesc: 'অটো-বাসের সরকারি ভাড়া ও সঠিক দাম',
    cardComplaintTitle: 'অভিযোগ ও তথ্য যাচাই',
    cardComplaintDesc: 'অতিরিক্ত টাকা নিলে অভিযোগ ও SOS',
    crowdStatus: 'ভিড়',
    lowCrowd: 'স্বাভাবিক',
    modCrowd: 'মাঝারি',
    highCrowd: 'প্রচণ্ড',
    darshanTimings: 'দর্শনের সময়',

    mapTitle: 'তীর্থ মানচিত্র',
    mapSubtitle: 'সঠিক পথনির্দেশ',
    filterAll: 'সকল',
    filterGhats: 'ঘাট',
    filterTemples: 'মন্দির',
    filterFood: 'অন্নছত্র',
    filterMedical: 'চিকিৎসা',
    closeMap: 'মানচিত্র বন্ধ করুন',

    marketTitle: 'স্থানীয় বাজার',
    marketSubtitle: 'নিবন্ধিত দোকান ও নির্দিষ্ট দাম',
    allCategories: 'সকল',
    catChivda: 'চিঁড়ে ও মিষ্টি',
    catFood: 'খাবার ও মিসল',
    catPuja: 'পূজা সামগ্রী',
    catGrapes: 'আঙুর ও কিসমিস',
    catStay: 'ধর্মশালা',
    govtApprovedPrice: 'সরকারি দাম',
    rateThisShop: 'রেটিং দিন',
    submitRating: 'রেটিং জমা দিন',
    writeReview: 'মতামত লিখুন',
    shopContact: 'যোগাযোগ করুন',

    fareTitle: 'সরকারি ভাড়া তালিকা',
    fareSubtitle: 'প্রশাসন নির্ধারিত দর',
    fromLocation: 'কোথা থেকে',
    toLocation: 'কোথায়',
    selectRoute: 'রুট ভাড়া',
    sharedAuto: 'শেয়ারিং অটো',
    privateAuto: 'প্রাইভেট অটো',
    kumbhBus: 'সিটি বাস',
    perPerson: 'জনপ্রতি',
    standardFoodRates: 'নির্ধারিত দাম',
    standardRatesNote: 'সরকারি সর্বোচ্চ দাম। হেল্প ট্যাবে অভিযোগ করুন।',

    complaintTabTitle: 'অভিযোগ ও জরুরি সেবা',
    complaintTabSubtitle: '২৪ ঘণ্টা প্রশাসন নজরদারি',
    sectionReportOvercharge: 'অতিরিক্ত মূল্য আদায়ের অভিযোগ',
    sectionRumorBuster: 'তথ্য যাচাই (Fact-Check)',
    sectionEmergency: 'জরুরি হেল্পলাইন (SOS)',
    selectCategory: 'ধরন',
    vehicleOrShop: 'গাড়ির নম্বর বা দোকানের নাম',
    standardAmt: 'সরকারি দাম (₹)',
    chargedAmt: 'দাবি করা টাকা (₹)',
    locationPlace: 'স্থান',
    submitComplaint: 'অভিযোগ জমা দিন',
    complaintSuccess: 'অভিযোগ নথিভুক্ত। টোকেন তৈরি হয়েছে।',
    reportRumorBtn: 'যাচাইয়ের জন্য পাঠান',
    rumorPlaceholder: 'তথ্য এখানে লিখুন...',
    emergencyDesc: 'জরুরি ডাইরেক্ট কল',
  },

  ta: {
    appName: 'கும்பசேது',
    appTagline: 'நாசிக் கும்பமேளா 2027',
    welcome: 'கும்பமேளா வழிகாட்டி',
    selectLanguage: 'மொழி தேர்வு',
    changeLanguage: 'மொழி மாற்றுக',
    listenVoice: 'ஆடியோ',
    speaking: 'இயங்குகிறது...',
    save: 'சேமி',
    cancel: 'ரத்து',
    search: 'தேடு...',
    call: 'அழை',
    direction: 'வழி',
    verified: 'சரிபார்க்கப்பட்டது',
    fakeNews: 'தவறான தகவல்',
    underReview: 'ஆய்வில் உள்ளது',
    shahiSnan: 'நீராடல் நாட்கள்',

    regTitle: 'பக்தர் பதிவு',
    regSubtitle: 'பெயர், தொலைபேசி, பிறந்த தேதி',
    fullNameLabel: 'முழு பெயர்',
    fullNamePlaceholder: 'எ.கா. செந்தில் குமார்',
    phoneLabel: 'கைபேசி எண்',
    phonePlaceholder: '10 இலக்க எண்',
    dobLabel: 'பிறந்த தேதி',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'தொடர்க',
    welcomePilgrim: 'பக்தர்',
    fillAllFields: 'விவரங்களை நிரப்பவும்',

    tabHome: 'முகப்பு',
    tabMarket: 'சந்தை',
    tabFare: 'கட்டணம்',
    tabHelp: 'புகார் & SOS',

    homeBannerTitle: 'புனித தலங்கள் & கரைகள்',
    homeBannerSub: 'ராம்குண்ட், திரியம்பகேஷ்வர், பஞ்சவடி',
    openPilgrimMapBtn: 'வரைபடம்',
    quickFeatures: 'முக்கிய வசதிகள்',
    cardPilgrimTitle: 'கோயில் & ঘাট வரைபடம்',
    cardPilgrimDesc: 'கோயில்கள் மற்றும் நேரலை கூட்ட நெரிசல்',
    cardMarketTitle: 'உள்ளூர் சந்தை',
    cardMarketDesc: 'உள்ளூர் பொருட்கள், உணவகங்கள் & கடைகள்',
    cardFareTitle: 'கட்டண வழிகாட்டி',
    cardFareDesc: 'அரசு ஆட்டோ-பேருந்து கட்டணம் மற்றும் உணவு விலை',
    cardComplaintTitle: 'புகார் & தகவல் சரிபார்ப்பு',
    cardComplaintDesc: 'கூடுதல் கட்டண புகார் & அவசர எண்கள்',
    crowdStatus: 'கூட்டம்',
    lowCrowd: 'குறைவு',
    modCrowd: 'மிதமானது',
    highCrowd: 'அதிகம்',
    darshanTimings: 'தரிசன நேரம்',

    mapTitle: 'புனித வரைபடம்',
    mapSubtitle: 'நேரடி வழிகாட்டல்',
    filterAll: 'அனைத்தும்',
    filterGhats: 'கரைகள்',
    filterTemples: 'கோயில்கள்',
    filterFood: 'அன்னதானம்',
    filterMedical: 'மருத்துவம்',
    closeMap: 'மூடுக',

    marketTitle: 'உள்ளூர் சந்தை',
    marketSubtitle: 'அரசு அங்கீகரித்த கடைகள்',
    allCategories: 'அனைத்தும்',
    catChivda: 'சிவ்டா & இனிப்புகள்',
    catFood: 'உணவு',
    catPuja: 'பூஜை பொருட்கள்',
    catGrapes: 'திராட்சை',
    catStay: 'விடுதிகள்',
    govtApprovedPrice: 'அரசு விலை',
    rateThisShop: 'மதிப்பிடுக',
    submitRating: 'சமர்ப்பி',
    writeReview: 'கருத்து எழுதுக',
    shopContact: 'தொடர்பு கொள்க',

    fareTitle: 'அரசு கட்டணப் பட்டியல்',
    fareSubtitle: 'அரசு நிர்ணயித்த கட்டணங்கள்',
    fromLocation: 'புறப்பாடு',
    toLocation: 'சேருமிடம்',
    selectRoute: 'பாதை கட்டணம்',
    sharedAuto: 'பகிர்வு ஆட்டோ',
    privateAuto: 'தனி ஆட்டோ',
    kumbhBus: 'பேருந்து',
    perPerson: 'நபருக்கு',
    standardFoodRates: 'நிலையான விலைகள்',
    standardRatesNote: 'அரசு அதிகபட்ச விலை. புகார் பகுதியில் தெரிவிக்கவும்.',

    complaintTabTitle: 'புகார் & அவசர உதவி',
    complaintTabSubtitle: '24x7 அரசு கண்காணிப்பு',
    sectionReportOvercharge: 'கூடுதல் கட்டண புகார்',
    sectionRumorBuster: 'வதந்தி தடுப்பு',
    sectionEmergency: 'அவசர எண்கள் (SOS)',
    selectCategory: 'வகை',
    vehicleOrShop: 'வாகன எண் அல்லது கடை பெயர்',
    standardAmt: 'அரசு கட்டணம் (₹)',
    chargedAmt: 'கேட்ட தொகை (₹)',
    locationPlace: 'இடம்',
    submitComplaint: 'புகார் அளிக்கவும்',
    complaintSuccess: 'புகார் பதிவானது. டோக்கன் உருவானது.',
    reportRumorBtn: 'சரிபார்க்க அனுப்புக',
    rumorPlaceholder: 'தகவலை இங்கே உள்ளிடுக...',
    emergencyDesc: 'நேரடி அவசர அழைப்பு',
  },

  te: {
    appName: 'కుంభసేతు',
    appTagline: 'నాసిక్ కుంభమేళా 2027',
    welcome: 'కుంభమేళా గైడ్',
    selectLanguage: 'భాష ఎంచుకోండి',
    changeLanguage: 'భాష మార్చండి',
    listenVoice: 'ఆడియో గైడ్',
    speaking: 'ప్లే అవుతోంది...',
    save: 'సేవ్',
    cancel: 'రద్దు',
    search: 'వెతకండి...',
    call: 'కాల్',
    direction: 'మార్గం',
    verified: 'ధృవీకరించబడింది',
    fakeNews: 'తప్పుడు సమాచారం',
    underReview: 'పరిశీలనలో ఉంది',
    shahiSnan: 'స్నాన దినాలు',

    regTitle: 'భక్తుల నమోదు',
    regSubtitle: 'పేరు, ఫోన్ నంబర్, పుట్టిన తేదీ',
    fullNameLabel: 'పూర్తి పేరు',
    fullNamePlaceholder: 'ఉదా. రమేష్ వర్మ',
    phoneLabel: 'మొబైల్ నంబర్',
    phonePlaceholder: '10 అంకెల నంబర్',
    dobLabel: 'పుట్టిన తేదీ',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'కొనసాగించండి',
    welcomePilgrim: 'భక్తుడు',
    fillAllFields: 'అన్ని వివరాలు పూరించండి',

    tabHome: 'హోమ్',
    tabMarket: 'మార్కెట్',
    tabFare: 'ఛార్జీలు',
    tabHelp: 'ఫిర్యాదు & SOS',

    homeBannerTitle: 'తీర్థక్షేత్రాలు & ఘాట్లు',
    homeBannerSub: 'రామకుండ్, త్రయంబకేశ్వర్, పంచవటి దర్శనం',
    openPilgrimMapBtn: 'మ్యాప్ తెరవండి',
    quickFeatures: 'ముఖ్య సేవలు',
    cardPilgrimTitle: 'తీర్థ & ఘాట్ మ్యాప్',
    cardPilgrimDesc: 'గుడులు, స్నాన ఘాట్లు మరియు రద్దీ స్థాయి',
    cardMarketTitle: 'స్థానిక మార్కెట్',
    cardMarketDesc: 'ప్రసిద్ధ వస్తువులు, భోజనం మరియు దుకాణాలు',
    cardFareTitle: 'ఛార్జీల జాబితా',
    cardFareDesc: 'ఆటో-బస్సు ఛార్జీలు మరియు ఆహార ధరలు',
    cardComplaintTitle: 'ఫిర్యాదులు & నిజనిర్ధారణ',
    cardComplaintDesc: 'అదనపు వసూళ్ల ఫిర్యాదు మరియు SOS',
    crowdStatus: 'రద్దీ',
    lowCrowd: 'తక్కువ',
    modCrowd: 'మధ్యస్థం',
    highCrowd: 'ఎక్కువ',
    darshanTimings: 'దర్శన వేళలు',

    mapTitle: 'తీర్థ మ్యాప్',
    mapSubtitle: 'నావిగేషన్',
    filterAll: 'అన్నీ',
    filterGhats: 'ఘాట్లు',
    filterTemples: 'గుడులు',
    filterFood: 'అన్నదానం',
    filterMedical: 'వైద్యం',
    closeMap: 'మ్యాప్ మూసివేయి',

    marketTitle: 'స్థానిక మార్కెట్',
    marketSubtitle: 'ధృవీకరించిన దుకాణాలు & స్థిర ధరలు',
    allCategories: 'అన్నీ',
    catChivda: 'మిఠాయి & స్నాక్స్',
    catFood: 'భోజనం',
    catPuja: 'పూజా సామాగ్రి',
    catGrapes: 'ద్రాక్ష',
    catStay: 'వసతి',
    govtApprovedPrice: 'ప్రభుత్వ ధర',
    rateThisShop: 'రేటింగ్ ఇవ్వండి',
    submitRating: 'సమర్పించండి',
    writeReview: 'సమీక్ష రాయండి',
    shopContact: 'సంప్రదించండి',

    fareTitle: 'ప్రభుత్వ ఛార్జీల పట్టిక',
    fareSubtitle: 'అధికారిక ధరల జాబితా',
    fromLocation: 'ఎక్కడ నుండి',
    toLocation: 'ఎక్కడికి',
    selectRoute: 'రూట్ ఛార్జీ',
    sharedAuto: 'షేరింగ్ ఆటో',
    privateAuto: 'ప్రైవేట్ ఆటో',
    kumbhBus: 'సిటీ బస్సు',
    perPerson: 'ఒక్కొక్కరికి',
    standardFoodRates: 'ప్రామాణిక ధరలు',
    standardRatesNote: 'ప్రభుత్వ గరిష్ట ధరలు. సహాయ విభాగంలో ఫిర్యాదు చేయండి.',

    complaintTabTitle: 'ఫిర్యాదు & అత్యవసరం',
    complaintTabSubtitle: '24 గంటల పర్యవేక్షణ',
    sectionReportOvercharge: 'అదనపు ఛార్జీల ఫిర్యాదు',
    sectionRumorBuster: 'వదంతుల నివారణ (Fact-Check)',
    sectionEmergency: 'అత్యవసర నంబర్లు (SOS)',
    selectCategory: 'వర్గం',
    vehicleOrShop: 'వాహనం నంబర్ లేదా దుకాణం పేరు',
    standardAmt: 'ప్రభుత్వ ధర (₹)',
    chargedAmt: 'వసూలు చేసిన మొత్తం (₹)',
    locationPlace: 'ప్రాంతం',
    submitComplaint: 'ఫిర్యాదు చేయండి',
    complaintSuccess: 'ఫిర్యాదు నమోదైంది. టోకెన్ జారీ చేయబడింది.',
    reportRumorBtn: 'పరిశీలనకు పంపండి',
    rumorPlaceholder: 'సమాచారాన్ని నమోదు చేయండి...',
    emergencyDesc: 'నేరుగా అత్యవసర కాల్',
  },

  kn: {
    appName: 'ಕುಂಭಸೇತು',
    appTagline: 'ನಾಸಿಕ್ ಕುಂಭಮೇಳ 2027',
    welcome: 'ಕುಂಭಮೇಳ ಮಾರ್ಗದರ್ಶಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    changeLanguage: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
    listenVoice: 'ಆಡಿಯೋ',
    speaking: 'ಪ್ಲೇ ಆಗುತ್ತಿದೆ...',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದು',
    search: 'ಹುಡುಕಿ...',
    call: 'ಕರೆ',
    direction: 'ಮಾರ್ಗ',
    verified: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    fakeNews: 'ಸುಳ್ಳು ಸುದ್ದಿ',
    underReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    shahiSnan: 'ಸ್ನಾನ ದಿನಾಂಕಗಳು',

    regTitle: 'ಭಕ್ತರ ನೋಂದಣಿ',
    regSubtitle: 'ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ಜನ್ಮ ದಿನಾಂಕ',
    fullNameLabel: 'ಪೂರ್ಣ ಹೆಸರು',
    fullNamePlaceholder: 'ಉದಾ. ಸುರೇಶ್ ಕುಮಾರ್',
    phoneLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    phonePlaceholder: '10 ಅಂಕಿಗಳ ಸಂಖ್ಯೆ',
    dobLabel: 'ಜನ್ಮ ದಿನಾಂಕ',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'ಮುಂದುವರಿಯಿರಿ',
    welcomePilgrim: 'ಭಕ್ತ',
    fillAllFields: 'ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',

    tabHome: 'ಮುಖಪುಟ',
    tabMarket: 'ಮಾರುಕಟ್ಟೆ',
    tabFare: 'ದರಪಟ್ಟಿ',
    tabHelp: 'ದೂರು & SOS',

    homeBannerTitle: 'ಪವಿತ್ರ ತೀರ್ಥಕ್ಷೇತ್ರ & ಘಾಟ್‌ಗಳು',
    homeBannerSub: 'ರಾಮಕುಂಡ್, ತ್ರ್ಯಂಬಕೇಶ್ವರ, ಪಂಚವಟಿ ದರ್ಶನ',
    openPilgrimMapBtn: 'ನಕ್ಷೆ ತೆರೆಯಿರಿ',
    quickFeatures: 'ಪ್ರಮುಖ ಸೌಲಭ್ಯಗಳು',
    cardPilgrimTitle: 'ತೀರ್ಥ & ಘಾಟ್ ನಕ್ಷೆ',
    cardPilgrimDesc: 'ದೇವಾಲಯಗಳು ಮತ್ತು ಲೈವ್ ಜನಸಂದಣಿ',
    cardMarketTitle: 'ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ',
    cardMarketDesc: 'ವಿಶೇಷ ತಿನಿಸುಗಳು, ದ್ರಾಕ್ಷಿ & ಅಂಗಡಿಗಳು',
    cardFareTitle: 'ದರಪಟ್ಟಿ',
    cardFareDesc: 'ಆಟೋ-ಬಸ್ ದರಗಳು ಮತ್ತು ಊಟದ ನಿಗದಿತ ಬೆಲೆ',
    cardComplaintTitle: 'ದೂರು & ಸತ್ಯಾಸತ್ಯತೆ',
    cardComplaintDesc: 'ಹೆಚ್ಚುವರಿ ದರ ವಸೂಲಿ ದೂರು ಮತ್ತು SOS',
    crowdStatus: 'ಜನಸಂದಣಿ',
    lowCrowd: 'ಕಡಿಮೆ',
    modCrowd: 'ಮಧ್ಯಮ',
    highCrowd: 'ಹೆಚ್ಚು',
    darshanTimings: 'ದರ್ಶನ ಸಮಯ',

    mapTitle: 'ತೀರ್ಥ ನಕ್ಷೆ',
    mapSubtitle: 'ನಿಖರ ಮಾರ್ಗದರ್ಶನ',
    filterAll: 'ಎಲ್ಲಾ',
    filterGhats: 'ಘಾಟ್‌ಗಳು',
    filterTemples: 'ದೇವಾಲಯಗಳು',
    filterFood: 'ಅನ್ನದಾಸೋಹ',
    filterMedical: 'ವೈದ್ಯಕೀಯ',
    closeMap: 'ನಕ್ಷೆ ಮುಚ್ಚಿ',

    marketTitle: 'ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ',
    marketSubtitle: 'ನೋಂದಾಯಿತ ಅಂಗಡಿಗಳು',
    allCategories: 'ಎಲ್ಲಾ',
    catChivda: 'ಚಿವ್ಡಾ & ಸಿಹಿ',
    catFood: 'ಊಟ & ಉಪಹಾರ',
    catPuja: 'ಪೂಜಾ ಸಾಮಗ್ರಿ',
    catGrapes: 'ದ್ರಾಕ್ಷಿ',
    catStay: 'ವಸತಿ',
    govtApprovedPrice: 'ಸರ್ಕಾರಿ ದರ',
    rateThisShop: 'ರೇಟಿಂಗ್ ನೀಡಿ',
    submitRating: 'ಸಲ್ಲಿಸಿ',
    writeReview: 'ಅಭಿಪ್ರಾಯ ಬರೆಯಿರಿ',
    shopContact: 'ಸಂಪರ್ಕಿಸಿ',

    fareTitle: 'ಸರ್ಕಾರಿ ದರಪಟ್ಟಿ',
    fareSubtitle: 'ನಿಗದಿತ ಶುಲ್ಕಗಳು',
    fromLocation: 'ಎಲ್ಲಿಂದ',
    toLocation: 'ಎಲ್ಲಿಗೆ',
    selectRoute: 'ಮಾರ್ಗ ದರ',
    sharedAuto: 'ಶೇರಿಂಗ್ ಆಟೋ',
    privateAuto: 'ಖಾಸಗಿ ಆಟೋ',
    kumbhBus: 'ಸಿಟಿ ಬಸ್',
    perPerson: 'ಪ್ರತಿ ವ್ಯಕ್ತಿಗೆ',
    standardFoodRates: 'ನಿಗದಿತ ದರಗಳು',
    standardRatesNote: 'ಸರ್ಕಾರಿ ಗರಿಷ್ಠ ದರಗಳು. ಹೆಲ್ಪ್ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ದೂರು ದಾಖಲಿಸಿ.',

    complaintTabTitle: 'ದೂರು & ತುರ್ತು ಸೇವೆ',
    complaintTabSubtitle: '24 ಗಂಟೆಗಳ ನಿಗಾ',
    sectionReportOvercharge: 'ಹೆಚ್ಚುವರಿ ದರ ವಸೂಲಿ ದೂರು',
    sectionRumorBuster: 'ಸುಳ್ಳು ಸುದ್ದಿ ತಡೆ (Fact-Check)',
    sectionEmergency: 'ತುರ್ತು ಸಹಾಯವಾಣಿ (SOS)',
    selectCategory: 'ವರ್ಗ',
    vehicleOrShop: 'ವಾಹನ ಸಂಖ್ಯೆ ಅಥವಾ ಅಂಗಡಿ ಹೆಸರು',
    standardAmt: 'ಸರ್ಕಾರಿ ದರ (₹)',
    chargedAmt: 'ಪಡೆದ ಮೊತ್ತ (₹)',
    locationPlace: 'ಸ್ಥಳ',
    submitComplaint: 'ದೂರು ಸಲ್ಲಿಸಿ',
    complaintSuccess: 'ದೂರು ದಾಖಲಾಗಿದೆ. ಟೋಕನ್ ಸೃಷ್ಟಿಯಾಗಿದೆ.',
    reportRumorBtn: 'ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಿ',
    rumorPlaceholder: 'ಮಾಹಿತಿಯನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ...',
    emergencyDesc: 'ನೇರ ತುರ್ತು ಕರೆ',
  },

  ml: {
    appName: 'കുംഭസേതു',
    appTagline: 'നാസിക് കുംഭമേള 2027',
    welcome: 'കുംഭമേള ഗൈഡ്',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    listenVoice: 'ഓഡിയോ',
    speaking: 'പ്ലേ ചെയ്യുന്നു...',
    save: 'സേവ്',
    cancel: 'റദ്ദാക്കുക',
    search: 'തിരയുക...',
    call: 'വിളിക്കുക',
    direction: 'റൂട്ട്',
    verified: 'സ്ഥിരീകരിച്ചത്',
    fakeNews: 'വ്യാജ വാർത്ത',
    underReview: 'പരിശോധനയിൽ',
    shahiSnan: 'സ്നാന തീയതികൾ',

    regTitle: 'തീർത്ഥാടക രജിസ്ട്രേഷൻ',
    regSubtitle: 'പേര്, ഫോൺ നമ്പർ, ജനനത്തീയതി',
    fullNameLabel: 'പൂർണ്ണ നാമം',
    fullNamePlaceholder: 'ഉദാ: പ്രകാശ് മേനോൻ',
    phoneLabel: 'മൊബൈൽ നമ്പർ',
    phonePlaceholder: '10 അക്ക നമ്പർ',
    dobLabel: 'ജനനത്തീയതി',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'തുടരുക',
    welcomePilgrim: 'തീർത്ഥാടകൻ',
    fillAllFields: 'എല്ലാ വിവരങ്ങളും പൂരിപ്പിക്കുക',

    tabHome: 'ഹോം',
    tabMarket: 'വിപണി',
    tabFare: 'നിരക്കുകൾ',
    tabHelp: 'പരാതി & SOS',

    homeBannerTitle: 'തീർത്ഥാടന കേന്ദ്രങ്ങൾ & ഘട്ടുകൾ',
    homeBannerSub: 'രാംകുണ്ഡ്, ത്രയംബകേശ്വർ, പഞ്ചവടി ദർശനം',
    openPilgrimMapBtn: 'മാപ്പ് തുറക്കുക',
    quickFeatures: 'പ്രധാന സേവനങ്ങൾ',
    cardPilgrimTitle: 'ക്ഷേത്ര & ഘട്ട് മാപ്പ്',
    cardPilgrimDesc: 'ക്ഷേത്രങ്ങൾ, ഘട്ടുകൾ, തത്സമയ തിരക്ക്',
    cardMarketTitle: 'പ്രാദേശിക വിപണി',
    cardMarketDesc: 'വിഭവങ്ങൾ, മുന്തിരി, ഭക്ഷണശാലകൾ',
    cardFareTitle: 'നിരക്ക് വിവരങ്ങൾ',
    cardFareDesc: 'ഓട്ടോ-ബസ് നിരക്കുകൾ, ഭക്ഷണ വിലകൾ',
    cardComplaintTitle: 'പരാതികളും വസ്തുതാ പരിശോധനയും',
    cardComplaintDesc: 'അധിക നിരക്ക് ഈടാക്കൽ പരാതി, SOS',
    crowdStatus: 'തിരക്ക്',
    lowCrowd: 'കുറഞ്ഞ തിരക്ക്',
    modCrowd: 'മിതമായ തിരക്ക്',
    highCrowd: 'കൂടിയ തിരക്ക്',
    darshanTimings: 'ദർശന സമയം',

    mapTitle: 'തീർത്ഥാടക മാപ്പ്',
    mapSubtitle: 'വഴികാട്ടി',
    filterAll: 'എല്ലാം',
    filterGhats: 'ഘട്ടുകൾ',
    filterTemples: 'ക്ഷേത്രങ്ങൾ',
    filterFood: 'അന്നദാനം',
    filterMedical: 'ചികിത്സ',
    closeMap: 'മാപ്പ് അടയ്ക്കുക',

    marketTitle: 'പ്രാദേശിക വിപണി',
    marketSubtitle: 'അംഗീകൃത കടകൾ & നിശ്ചിത നിരക്കുകൾ',
    allCategories: 'എല്ലാം',
    catChivda: 'ചിസ്ന & പലഹാരങ്ങൾ',
    catFood: 'ഭക്ഷണം',
    catPuja: 'പൂജാ സാധനങ്ങൾ',
    catGrapes: 'മുന്തിരി',
    catStay: 'താമസം',
    govtApprovedPrice: 'സർക്കാർ നിരക്ക്',
    rateThisShop: 'റേറ്റിംഗ് നൽകുക',
    submitRating: 'സമർപ്പിക്കുക',
    writeReview: 'അഭിപ്രായം രേഖപ്പെടുത്തുക',
    shopContact: 'ബന്ധപ്പെടുക',

    fareTitle: 'ഔദ്യോഗിക നിരക്കുകൾ',
    fareSubtitle: 'നിശ്ചയിച്ച യാത്രാനിരക്കുകൾ',
    fromLocation: 'എവിടെ നിന്ന്',
    toLocation: 'എങ്ങോട്ട്',
    selectRoute: 'റൂട്ട് നിരക്ക്',
    sharedAuto: 'ഷെയർ ഓട്ടോ',
    privateAuto: 'പ്രൈവറ്റ് ഓട്ടോ',
    kumbhBus: 'സിറ്റി ബസ്',
    perPerson: 'ഒരാൾക്ക്',
    standardFoodRates: 'നിശ്ചിത നിരക്കുകൾ',
    standardRatesNote: 'സർക്കാർ പരമാവധി നിരക്കുകൾ. ഹെൽപ്പ് ടാബിൽ പരാതിപ്പെടുക.',

    complaintTabTitle: 'പരാതിയും അടിയന്തര സഹായവും',
    complaintTabSubtitle: '24 മണിക്കൂർ നിരീക്ഷണം',
    sectionReportOvercharge: 'അധിക നിരക്ക് ഈടാക്കൽ പരാതി',
    sectionRumorBuster: 'വസ്തുതാ പരിശോധന (Fact-Check)',
    sectionEmergency: 'അടിയന്തര നമ്പറുകൾ (SOS)',
    selectCategory: 'വിഭാഗം',
    vehicleOrShop: 'വാഹന നമ്പർ അല്ലെങ്കിൽ കടയുടെ പേര്',
    standardAmt: 'സർക്കാർ നിരക്ക് (₹)',
    chargedAmt: 'വാങ്ങിയ തുക (₹)',
    locationPlace: 'സ്ഥലം',
    submitComplaint: 'പരാതി നൽകുക',
    complaintSuccess: 'പരാതി രജിസ്റ്റർ ചെയ്തു. ടോക്കൺ ലഭിച്ചു.',
    reportRumorBtn: 'പരിശോധനയ്ക്ക് അയക്കുക',
    rumorPlaceholder: 'വിവരങ്ങൾ ഇവിടെ രേഖപ്പെടുത്തുക...',
    emergencyDesc: 'നേരിട്ടുള്ള അടിയന്തര കോൾ',
  },

  pa: {
    appName: 'ਕੁੰਭਸੇਤੂ',
    appTagline: 'ਨਾਸਿਕ ਕੁੰਭ ਮੇਲਾ 2027',
    welcome: 'ਕੁੰਭ ਮੇਲਾ ਗਾਈਡ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    listenVoice: 'ਆਡੀਓ ਗਾਈਡ',
    speaking: 'ਚੱਲ ਰਿਹਾ ਹੈ...',
    save: 'ਸੇਵ',
    cancel: 'ਰੱਦ ਕਰੋ',
    search: 'ਖੋਜੋ...',
    call: 'ਕਾਲ',
    direction: 'ਰਸਤਾ',
    verified: 'ਪ੍ਰਮਾਣਿਤ',
    fakeNews: 'ਗਲਤ ਦਾਅਵਾ',
    underReview: 'ਜਾਂਚ ਜਾਰੀ',
    shahiSnan: 'ਸ਼ਾਹੀ ਇਸ਼ਨਾਨ ਮਿਤੀਆਂ',

    regTitle: 'ਸ਼ਰਧਾਲੂ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    regSubtitle: 'ਨਾਮ, ਮੋਬਾਈਲ ਨੰਬਰ ਅਤੇ ਜਨਮ ਮਿਤੀ',
    fullNameLabel: 'ਪੂਰਾ ਨਾਮ',
    fullNamePlaceholder: 'ਜਿਵੇਂ: ਹਰਪ੍ਰੀਤ ਸਿੰਘ',
    phoneLabel: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    phonePlaceholder: '10 ਅੰਕਾਂ ਦਾ ਨੰਬਰ',
    dobLabel: 'ਜਨਮ ਮਿਤੀ',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'ਅੱਗੇ ਵਧੋ',
    welcomePilgrim: 'ਸ਼ਰਧਾਲੂ',
    fillAllFields: 'ਸਾਰੀ ਜਾਣਕਾਰੀ ਭਰੋ',

    tabHome: 'ਹੋਮ',
    tabMarket: 'ਬਾਜ਼ਾਰ',
    tabFare: 'ਕਿਰਾਇਆ',
    tabHelp: 'ਸ਼ਿਕਾਇਤ ਤੇ SOS',

    homeBannerTitle: 'ਪਵਿੱਤਰ ਤੀਰਥ ਤੇ ਘਾਟ',
    homeBannerSub: 'ਰਾਮਕੁੰਡ, ਤ੍ਰਿਅੰਬਕੇਸ਼ਵਰ, ਪੰਚਵਟੀ ਦਰਸ਼ਨ',
    openPilgrimMapBtn: 'ਨਕਸ਼ਾ ਖੋਲ੍ਹੋ',
    quickFeatures: 'ਮੁੱਖ ਸੇਵਾਵਾਂ',
    cardPilgrimTitle: 'ਤੀਰਥ ਤੇ ਘਾਟ ਨਕਸ਼ਾ',
    cardPilgrimDesc: 'ਮੰਦਰ, ਘਾਟ ਅਤੇ ਲਾਈਵ ਭੀੜ',
    cardMarketTitle: 'ਸਥਾਨਕ ਬਾਜ਼ਾਰ',
    cardMarketDesc: 'ਚਿਵੜਾ, ਅੰਗੂਰ, ਖਾਣ-ਪੀਣ ਦੀਆਂ ਦੁਕਾਨਾਂ',
    cardFareTitle: 'ਕਿਰਾਇਆ ਸੂਚੀ',
    cardFareDesc: 'ਆਟੋ-ਬੱਸ ਕਿਰਾਇਆ ਤੇ ਖਾਣੇ ਦੇ ਤੈਅ ਰੇਟ',
    cardComplaintTitle: 'ਸ਼ਿਕਾਇਤ ਤੇ ਤੱਥ ਜਾਂਚ',
    cardComplaintDesc: 'ਵੱਧ ਪੈਸੇ ਵਸੂਲੀ ਦੀ ਸ਼ਿਕਾਇਤ ਤੇ SOS',
    crowdStatus: 'ਭੀੜ',
    lowCrowd: 'ਘੱਟ ਭੀੜ',
    modCrowd: 'ਦਰਮਿਆਨੀ ਭੀੜ',
    highCrowd: 'ਭਾਰੀ ਭੀੜ',
    darshanTimings: 'ਦਰਸ਼ਨ ਸਮਾਂ',

    mapTitle: 'ਤੀਰਥ ਨਕਸ਼ਾ',
    mapSubtitle: 'ਨੇਵੀਗੇਸ਼ਨ',
    filterAll: 'ਸਾਰੇ',
    filterGhats: 'ਘਾਟ',
    filterTemples: 'ਮੰਦਰ',
    filterFood: 'ਲੰਗਰ / ਭੋਜਨ',
    filterMedical: 'ਮੈਡੀਕਲ',
    closeMap: 'ਨਕਸ਼ਾ ਬੰਦ ਕਰੋ',

    marketTitle: 'ਸਥਾਨਕ ਬਾਜ਼ਾਰ',
    marketSubtitle: 'ਰਜਿਸਟਰਡ ਦੁਕਾਨਾਂ ਅਤੇ ਤੈਅ ਰੇਟ',
    allCategories: 'ਸਾਰੇ',
    catChivda: 'ਚਿਵੜਾ ਤੇ ਮਿਠਾਈ',
    catFood: 'ਭੋਜਨ',
    catPuja: 'ਪੂਜਾ ਸਮੱਗਰੀ',
    catGrapes: 'ਅੰਗੂਰ ਤੇ ਸੌਗੀ',
    catStay: 'ਧਰਮਸ਼ਾਲਾ',
    govtApprovedPrice: 'ਸਰਕਾਰੀ ਰੇਟ',
    rateThisShop: 'ਰੇਟਿੰਗ ਦਿਓ',
    submitRating: 'ਸਮਰਪਿਤ ਕਰੋ',
    writeReview: 'ਤਜਰਬਾ ਲਿਖੋ',
    shopContact: 'ਸੰਪਰਕ ਕਰੋ',

    fareTitle: 'ਸਰਕਾਰੀ ਕਿਰਾਇਆ ਸੂਚੀ',
    fareSubtitle: 'ਪ੍ਰਸ਼ਾਸਨ ਵੱਲੋਂ ਤੈਅ ਰੇਟ',
    fromLocation: 'ਕਿੱਥੋਂ',
    toLocation: 'ਕਿੱਥੇ',
    selectRoute: 'ਰੂਟ ਕਿਰਾਇਆ',
    sharedAuto: 'ਸ਼ੇਅਰਿੰਗ ਆਟੋ',
    privateAuto: 'ਪ੍ਰਾਈਵੇਟ ਆਟੋ',
    kumbhBus: 'ਸਿਟੀ ਬੱਸ',
    perPerson: 'ਪ੍ਰਤੀ ਵਿਅਕਤੀ',
    standardFoodRates: 'ਤੈਅ ਰੇਟ',
    standardRatesNote: 'ਸਰਕਾਰੀ ਵੱਧ ਤੋਂ ਵੱਧ ਰੇਟ। ਹੈਲਪ ਟੈਬ ਵਿੱਚ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ।',

    complaintTabTitle: 'ਸ਼ਿਕਾਇਤ ਅਤੇ ਐਮਰਜੈਂਸੀ',
    complaintTabSubtitle: '24 ਘੰਟੇ ਨਿਗਰਾਨੀ',
    sectionReportOvercharge: 'ਵੱਧ ਪੈਸੇ ਲੈਣ ਦੀ ਸ਼ਿਕਾਇਤ',
    sectionRumorBuster: 'ਤੱਥ ਜਾਂਚ (Fact-Check)',
    sectionEmergency: 'ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ (SOS)',
    selectCategory: 'ਸ਼੍ਰੇਣੀ',
    vehicleOrShop: 'ਗੱਡੀ ਨੰਬਰ ਜਾਂ ਦੁਕਾਨਦਾਰ ਦਾ ਨਾਮ',
    standardAmt: 'ਸਰਕਾਰੀ ਰੇਟ (₹)',
    chargedAmt: 'ਮੰਗੇ ਗਏ ਪੈਸੇ (₹)',
    locationPlace: 'ਸਥਾਨ',
    submitComplaint: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    complaintSuccess: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਹੋ ਗਈ। ਟੋਕਨ ਜਾਰੀ।',
    reportRumorBtn: 'ਜਾਂਚ ਲਈ ਭੇਜੋ',
    rumorPlaceholder: 'ਜਾਣਕਾਰੀ ਇੱਥੇ ਲਿਖੋ...',
    emergencyDesc: 'ਸਿੱਧੀ ਐਮਰਜੈਂਸੀ ਕਾਲ',
  },

  or: {
    appName: 'କୁମ୍ଭସେତୁ',
    appTagline: 'ନାସିକ କୁମ୍ଭମେଳା ୨୦୨୭',
    welcome: 'କୁମ୍ଭମେଳା ମାର୍ଗଦର୍ଶିକା',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    changeLanguage: 'ଭାଷା ବଦଳାନ୍ତୁ',
    listenVoice: 'ଅଡିଓ',
    speaking: 'ଚାଲୁଛି...',
    save: 'ସାଇତନ୍ତୁ',
    cancel: 'ବାତିଲ',
    search: 'ଖୋଜନ୍ତୁ...',
    call: 'କଲ୍',
    direction: 'ମାର୍ଗ',
    verified: 'ଯାଞ୍ଚ ହୋଇଛି',
    fakeNews: 'ଭୁଲ୍ ତଥ୍ୟ',
    underReview: 'ଯାଞ୍ଚ ଚାଲିଛି',
    shahiSnan: 'ଶାହୀ ସ୍ନାନ ତାରିଖ',

    regTitle: 'ତୀର୍ଥଯାତ୍ରୀ ପଞ୍ଜୀକରଣ',
    regSubtitle: 'ନାମ, ମୋବାଇଲ୍ ନମ୍ବର ଓ ଜନ୍ମ ତାରିଖ',
    fullNameLabel: 'ପୂରା ନାମ',
    fullNamePlaceholder: 'ଯଥା: ସୁଶାନ୍ତ ପଟ୍ଟନାୟକ',
    phoneLabel: 'ମୋବାଇଲ୍ ନମ୍ବର',
    phonePlaceholder: '୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ନମ୍ବର',
    dobLabel: 'ଜନ୍ମ ତାରିଖ',
    dobPlaceholder: 'DD/MM/YYYY',
    registerButton: 'ଆଗକୁ ବଢ଼ନ୍ତୁ',
    welcomePilgrim: 'ତୀର୍ଥଯାତ୍ରୀ',
    fillAllFields: 'ସମସ୍ତ ତଥ୍ୟ ପୂରଣ କରନ୍ତୁ',

    tabHome: 'ହୋମ୍',
    tabMarket: 'ବଜାର',
    tabFare: 'ଭଡ଼ା',
    tabHelp: 'ଅଭିଯୋଗ ଓ SOS',

    homeBannerTitle: 'ପବିତ୍ର ତୀର୍ଥ ଓ ସ୍ନାନ ଘାଟ',
    homeBannerSub: 'ରାମକୁଣ୍ଡ, ତ୍ର୍ୟମ୍ବକେଶ୍ୱର, ପଞ୍ଚବଟୀ ଦର୍ଶନ',
    openPilgrimMapBtn: 'ମ୍ୟାପ୍ ଖୋଲନ୍ତୁ',
    quickFeatures: 'ମୁଖ୍ୟ ସେବା',
    cardPilgrimTitle: 'ତୀର୍ଥ ଓ ଘାଟ ମ୍ୟାପ୍',
    cardPilgrimDesc: 'ମନ୍ଦିର, ଘାଟ ଓ ଲାଇଭ୍ ଭିଡ଼ ସ୍ଥିତି',
    cardMarketTitle: 'ସ୍ଥାନୀୟ ବଜାର',
    cardMarketDesc: 'ଚିଭଡ଼ା, ଅଙ୍ଗୁର, ଖାଦ୍ୟ ଓ ଦୋକାନ',
    cardFareTitle: 'ଭଡ଼ା ତାଲିକା',
    cardFareDesc: 'ଅଟୋ-ବସ୍ ଭଡ଼ା ଓ ଖାଦ୍ୟର ଉଚିତ୍ ଦର',
    cardComplaintTitle: 'ଅଭିଯୋଗ ଓ ତଥ୍ୟ ଯାଞ୍ଚ',
    cardComplaintDesc: 'ଅଧିକ ଟଙ୍କା ନେବା ଅଭିଯୋଗ ଓ SOS',
    crowdStatus: 'ଭିଡ଼',
    lowCrowd: 'କମ୍ ଭିଡ଼',
    modCrowd: 'ମଧ୍ୟମ ଭିଡ଼',
    highCrowd: 'ପ୍ରବଳ ଭିଡ଼',
    darshanTimings: 'ଦର୍ଶନ ସମୟ',

    mapTitle: 'ତୀର୍ଥ ମ୍ୟାପ୍',
    mapSubtitle: 'ମାର୍ଗଦର୍ଶନ',
    filterAll: 'ସମସ୍ତ',
    filterGhats: 'ଘାଟ',
    filterTemples: 'ମନ୍ଦିର',
    filterFood: 'ଅନ୍ନଛତ୍ର',
    filterMedical: 'ଚିକିତ୍ସା',
    closeMap: 'ମ୍ୟାପ୍ ବନ୍ଦ କରନ୍ତୁ',

    marketTitle: 'ସ୍ଥାନୀୟ ବଜାର',
    marketSubtitle: 'ପଞ୍ଜୀକୃତ ଦୋକାନ ଓ ନିର୍ଦ୍ଧାରିତ ଦର',
    allCategories: 'ସମସ୍ତ',
    catChivda: 'ଚିଭଡ଼ା ଓ ମିଠା',
    catFood: 'ଖାଦ୍ୟ',
    catPuja: 'ପୂଜା ସାମଗ୍ରୀ',
    catGrapes: 'ଅଙ୍ଗୁର ଓ କିସମିସ୍',
    catStay: 'ଧର୍ମଶାଳା',
    govtApprovedPrice: 'ସରକାରୀ ଦର',
    rateThisShop: 'ରେଟିଂ ଦିଅନ୍ତୁ',
    submitRating: 'ଦାଖଲ କରନ୍ତୁ',
    writeReview: 'ମତାମତ ଲେଖନ୍ତୁ',
    shopContact: 'ଯୋଗାଯୋଗ କରନ୍ତୁ',

    fareTitle: 'ସରକାରୀ ଭଡ଼ା ତାଲିକା',
    fareSubtitle: 'ପ୍ରଶାସନ ଦ୍ୱାରା ନିର୍ଦ୍ଧାରିତ ଦର',
    fromLocation: 'କେଉଁଠାରୁ',
    toLocation: 'କେଉଁଠାକୁ',
    selectRoute: 'ରୁଟ୍ ଭଡ଼ା',
    sharedAuto: 'ସେୟାରିଂ ଅଟୋ',
    privateAuto: 'ପ୍ରାଇଭେଟ୍ ଅଟୋ',
    kumbhBus: 'ସିଟି ବସ୍',
    perPerson: 'ଜଣ ପିଛା',
    standardFoodRates: 'ନିର୍ଦ୍ଧାରିତ ଦର',
    standardRatesNote: 'ସରକାରୀ ସର୍ବାଧିକ ଦର। ହେଲ୍ପ ଟ୍ୟାବରେ ଅଭିଯୋଗ କରନ୍ତୁ।',

    complaintTabTitle: 'ଅଭିଯୋଗ ଓ ଜରୁରୀ ସେବା',
    complaintTabSubtitle: '୨୪ ଘଣ୍ଟା ପ୍ରଶାସନ ତଦାରଖ',
    sectionReportOvercharge: 'ଅଧିକ ଟଙ୍କା ନେବା ଅଭିଯୋଗ',
    sectionRumorBuster: 'ତଥ୍ୟ ଯାଞ୍ଚ (Fact-Check)',
    sectionEmergency: 'ଜରୁରୀକାଳୀନ ହେଲ୍ପଲାଇନ୍ (SOS)',
    selectCategory: 'ବର୍ଗ',
    vehicleOrShop: 'ଗାଡ଼ି ନମ୍ବର କିମ୍ବା ଦୋକାନ ନାମ',
    standardAmt: 'ସରକାରୀ ଦର (₹)',
    chargedAmt: 'ନେଇଥିବା ଟଙ୍କା (₹)',
    locationPlace: 'ସ୍ଥାନ',
    submitComplaint: 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    complaintSuccess: 'ଅଭିଯୋଗ ଦାଖଲ ହେଲା। ଟୋକନ୍ ଜାରି।',
    reportRumorBtn: 'ଯାଞ୍ଚ ପାଇଁ ପଠାନ୍ତୁ',
    rumorPlaceholder: 'ତଥ୍ୟ ଏଠାରେ ଲେଖନ୍ତୁ...',
    emergencyDesc: 'ସିଧାସଳଖ ଜରୁରୀ କଲ୍',
  },
};
