# -*- coding: utf-8 -*-
"""Nashikkar Vendor & Police Administration translations for Kumbh Setu"""

NASHIKKAR_POLICE_TRANSLATIONS = {
    # Nashikkar Vendor Dashboard & Management
    "Civic Operator & Vendor Portal": { "mr": "नागरी चालक व विक्रेता पोर्टल", "hi": "नागरिक संचालक एवं विक्रेता पोर्टल", "en": "Civic Operator & Vendor Portal" },
    "Manage Stall, Rate Benchmarks & Orders": { "mr": "स्टॉल, दर मानक आणि ऑर्डर व्यवस्थापन", "hi": "स्टॉल, दर मानक एवं ऑर्डर प्रबंधन", "en": "Manage Stall, Rate Benchmarks & Orders" },
    "My Stall": { "mr": "माझा स्टॉल", "hi": "मेरा स्टॉल", "en": "My Stall" },
    "Orders": { "mr": "मागण्या / ऑर्डर्स", "hi": "ऑर्डर्स / मांग", "en": "Orders" },
    "Reviews": { "mr": "अभिप्राय / पुनरावलोकने", "hi": "समीक्षाएं / रेटिंग", "en": "Reviews" },
    "Fair Price": { "mr": "वाजवी दर", "hi": "उचित मूल्य", "en": "Fair Price" },
    "Exit": { "mr": "बाहेर पडा", "hi": "बाहर निकलें", "en": "Exit" },
    "Overview": { "mr": "सर्वसमावेशक आढावा", "hi": "अवलोकन", "en": "Overview" },
    "Vendors": { "mr": "विक्रेते", "hi": "विक्रेता", "en": "Vendors" },
    "Market": { "mr": "बाजार", "hi": "बाज़ार", "en": "Market" },
    "Bookings": { "mr": "नोंदणी", "hi": "बुकिंग", "en": "Bookings" },
    "Reports": { "mr": "तक्रारी व अहवाल", "hi": "रिपोर्ट्स", "en": "Reports" },
    "+ Register Vendor": { "mr": "+ नवीन विक्रेता नोंदणी", "hi": "+ नया विक्रेता पंजीकरण", "en": "+ Register Vendor" },
    "1. Full Name (संपूर्ण नाव)": { "mr": "१. संपूर्ण नाव", "hi": "१. पूरा नाम", "en": "1. Full Name (संपूर्ण नाव)" },
    "2. Email ID (ईमेल पत्ता)": { "mr": "२. ईमेल पत्ता", "hi": "२. ईमेल पता", "en": "2. Email ID (ईमेल पत्ता)" },
    "3. Mobile Number (मोबाईल क्रमांक)": { "mr": "३. मोबाईल क्रमांक", "hi": "३. मोबाइल नंबर", "en": "3. Mobile Number (मोबाईल क्रमांक)" },
    "4. Business / Stall Name (व्यवसाय / दुकानाचे नाव)": { "mr": "४. व्यवसाय / दुकानाचे नाव", "hi": "४. व्यवसाय / दुकान का नाम", "en": "4. Business / Stall Name" },
    "5. Stall Category (स्टॉल प्रकार)": { "mr": "५. स्टॉल प्रकार", "hi": "५. स्टॉल श्रेणी", "en": "5. Stall Category" },
    "6. Nashik Address / Sector (पत्ता / विभाग)": { "mr": "६. नाशिक पत्ता / विभाग", "hi": "६. नासिक पता / सेक्टर", "en": "6. Nashik Address / Sector" },
    "7. Fair Price Pledge (वाजवी दर शपथपत्र)": { "mr": "७. वाजवी दर शपथपत्र", "hi": "७. उचित मूल्य शपथ", "en": "7. Fair Price Pledge" },
    "I solemnly swear to adhere to certified statutory caps and never gouge pilgrims.": {
        "mr": "मी गांभीर्याने शपथ घेतो की मी प्रमाणित कमाल दरांचे पालन करेन आणि भाविकांकडून जादा दर घेणार नाही.",
        "hi": "मैं सत्यनिष्ठा से शपथ लेता हूँ कि मैं प्रमाणित अधिकतम दरों का पालन करूँगा और तीर्थयात्रियों से अधिक मूल्य नहीं वसूलूँगा।",
        "en": "I solemnly swear to adhere to certified statutory caps and never gouge pilgrims."
    },
    "Submit Vendor Registration": { "mr": "विक्रेता नोंदणी अर्ज सादर करा", "hi": "विक्रेता पंजीकरण आवेदन जमा करें", "en": "Submit Vendor Registration" },
    "Vendor ID / Registration No.": { "mr": "विक्रेता ओळख / नोंदणी क्रमांक", "hi": "विक्रेता पहचान / पंजीकरण संख्या", "en": "Vendor ID / Registration No." },
    "Registered Mobile Number": { "mr": "नोंदणीकृत मोबाईल क्रमांक", "hi": "पंजीकृत मोबाइल नंबर", "en": "Registered Mobile Number" },
    "Send OTP": { "mr": "ओटीपी पाठवा", "hi": "ओटीपी भेजें", "en": "Send OTP" },
    "Verify & Login": { "mr": "पडताळणी करा व प्रवेश करा", "hi": "सत्यापित करें और लॉगिन करें", "en": "Verify & Login" },
    "Active Stall Listings": { "mr": "सक्रिय स्टॉल नोंदी", "hi": "सक्रिय स्टॉल लिस्टिंग", "en": "Active Stall Listings" },
    "Total Orders Today": { "mr": "आजच्या एकूण ऑर्डर्स", "hi": "आज के कुल ऑर्डर्स", "en": "Total Orders Today" },
    "Fair Price Compliance Score": { "mr": "वाजवी दर अनुपालन गुण", "hi": "उचित मूल्य अनुपालन स्कोर", "en": "Fair Price Compliance Score" },
    "Customer Ratings": { "mr": "ग्राहक अभिप्राय", "hi": "ग्राहक रेटिंग", "en": "Customer Ratings" },
    "Statutory Fair Price Guidelines 2027": { "mr": "वैधानिक वाजवी दर मार्गदर्शक तत्त्वे २०२७", "hi": "वैधानिक उचित मूल्य दिशा-निर्देश २०२७", "en": "Statutory Fair Price Guidelines 2027" },
    "Reported Price Inconsistencies": { "mr": "नोंदवलेल्या दर विसंगती", "hi": "रिपोर्ट की गई मूल्य विसंगतियां", "en": "Reported Price Inconsistencies" },
    "Price Flags": { "mr": "दर इशारे", "hi": "मूल्य चेतावनी", "en": "Price Flags" },
    "Resolve Flag": { "mr": "समस्या निवारण करा", "hi": "समस्या का समाधान करें", "en": "Resolve Flag" },
    "Pending Review": { "mr": "तपासणी प्रलंबित", "hi": "समीक्षा लंबित", "en": "Pending Review" },
    "Verified Merchant": { "mr": "प्रमाणित व्यापारी", "hi": "सत्यापित व्यापारी", "en": "Verified Merchant" },

    # Police Administration & Central Command
    "Police & Security Administration Terminal": { "mr": "पोलीस व सुरक्षा प्रशासन टर्मिनल", "hi": "पुलिस एवं सुरक्षा प्रशासन टर्मिनल", "en": "Police & Security Administration Terminal" },
    "Simhastha Apex Security Unit • Zone A-1": { "mr": "सिंहस्थ सर्वोच्च सुरक्षा पथक • विभाग A-1", "hi": "सिंहस्थ शीर्ष सुरक्षा इकाई • ज़ोन A-1", "en": "Simhastha Apex Security Unit • Zone A-1" },
    "Officer Badge / ID": { "mr": "अधिकारी बिल्ला / ओळख क्रमांक", "hi": "अधिकारी बैज / आईडी", "en": "Officer Badge / ID" },
    "Official Secure PIN": { "mr": "अधिकृत सुरक्षा पिन", "hi": "आधिकारिक सुरक्षा पिन", "en": "Official Secure PIN" },
    "Duty Terminal Login": { "mr": "ड्युटी टर्मिनल लॉगिन", "hi": "ड्यूटी टर्मिनल लॉगिन", "en": "Duty Terminal Login" },
    "Escalations": { "mr": "तातडीच्या तक्रारी (Escalations)", "hi": "त्वरित मामले (Escalations)", "en": "Escalations" },
    "AI Radar": { "mr": "एआय गर्दी रडार", "hi": "एआई भीड़ रडार", "en": "AI Radar" },
    "Case Detail": { "mr": "प्रकरणाचा तपशील", "hi": "केस का विवरण", "en": "Case Detail" },
    "Case Log": { "mr": "नोंदवलेले खटले", "hi": "केस रजिस्टर", "en": "Case Log" },
    "Settings": { "mr": "सेटिंग्ज", "hi": "सेटिंग्स", "en": "Settings" },
    "Live Escalation Feed": { "mr": "थेट तक्रार प्रवाह", "hi": "लाइव शिकायत प्रवाह", "en": "Live Escalation Feed" },
    "Dispatch Patrol": { "mr": "गस्त पथक रवाना करा", "hi": "गश्ती दल रवाना करें", "en": "Dispatch Patrol" },
    "Investigate": { "mr": "चौकशी करा", "hi": "जांच करें", "en": "Investigate" },
    "Close Case": { "mr": "खटला निकाली काढा", "hi": "केस बंद करें", "en": "Close Case" },
    "High Alert": { "mr": "अतिदक्षतेचा इशारा", "hi": "हाई अलर्ट", "en": "High Alert" },
    "Moderate": { "mr": "मध्यम", "hi": "मध्यम", "en": "Moderate" },
    "Resolved": { "mr": "निकाली काढले", "hi": "सुलझाया गया", "en": "Resolved" },
    "Active Hotspots": { "mr": "सक्रिय गर्दी क्षेत्रे", "hi": "सक्रिय भीड़ क्षेत्र", "en": "Active Hotspots" },
    "Crowd Density Live": { "mr": "थेट गर्दी घनता", "hi": "लाइव भीड़ घनत्व", "en": "Crowd Density Live" },
    "Facial Recognition Vector Match": { "mr": "चेहरा ओळख पडताळणी", "hi": "चेहरा पहचान मिलान", "en": "Facial Recognition Vector Match" },
    "+ Add Officer Field Note": { "mr": "+ अधिकारी क्षेत्रीय नोंद जोडा", "hi": "+ अधिकारी फील्ड नोट जोड़ें", "en": "+ Add Officer Field Note" },
    "Police Terminal Settings": { "mr": "पोलीस टर्मिनल सेटिंग्ज", "hi": "पुलिस टर्मिनल सेटिंग्स", "en": "Police Terminal Settings" }
}
